Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2020-11, with the labels that each got.

#180 removing unused Azure dependency
  go.mod
  go.sum
Labels: cla-not-required

#181 Cherry-pick, Changes to use ipamdnsproviderprofiledomainlist which will make fetching the subdomain generic wrt dns provider type.
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  tests/avimockobjects/ipamdnsproviderprofiledomainlist_mock.json
  tests/bootuptests/bootupmock/ipamdnsproviderprofiledomainlist_mock.json
  tests/integrationtest/lib.go
Labels: cla-not-required

#178 Enable RHI as a AKO wide setting
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/lib/constants.go
  internal/lib/lib.go
  internal/rest/avi_obj_vs.go
  tests/integrationtest/l4_service_test.go
Labels: cla-not-required

#184 reboot controller in case up_since changes for avi ctrt leader
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  pkg/api/api.go
  pkg/api/api_fake.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#186 Be tolerant to ingresses without backends
  internal/nodes/ingress_model_rel.go
  internal/nodes/validator.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#187 Be tolerant to ingresses without backends
  internal/nodes/ingress_model_rel.go
  internal/nodes/validator.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#189 Changes to dockerfile and makefile
  Dockerfile.ako
  Makefile
  tests/integrationtest/l7_ingress_node_test.go
Labels: cla-not-required

#188 Changes to dockerfile and makefile
  Dockerfile.ako
  Makefile
  tests/integrationtest/l7_ingress_node_test.go
Labels: cla-not-required

#191 fix ingress status patch calls from #150
  internal/status/ing_status.go
Labels: cla-not-required

#192 static IP support for service LB using spec.loadbalancerIP
  internal/nodes/avi_model_l4_translator.go
  internal/rest/avi_obj_vs.go
  tests/advl4tests/advl4_hostname_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#185 Change the network profile to use FAST PATH
  internal/nodes/avi_model_l4_translator.go
  tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
  tests/integrationtest/l4_service_test.go
Labels: cla-not-required

#194 l7 pool name fix for nested paths
  internal/lib/lib.go
Labels: cla-not-required

#183 For Ingress: Namespace wise migration changes
  cmd/ako-main/main.go
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/lib/utils.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/status/ing_status.go
  pkg/utils/types.go
  pkg/utils/utils.go
Labels: cla-not-required

#196 Changes to dockerfile and makefile
  Dockerfile.ako
  Makefile
  tests/integrationtest/l7_ingress_node_test.go
Labels: cherry-pick-required, cla-not-required

#193 Support Tenancy in AKO.
  go.mod
  go.sum
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/lib.go
  internal/rest/avi_obj_vrf.go
  internal/rest/dequeue_nodes.go
  internal/retry/dequeue_retry.go
  tests/avimockobjects/tenant_mock.json
  tests/bootuptests/bootupmock/tenant_mock.json
  tests/integrationtest/lib.go
Labels: cla-not-required

#195 shutdown ako on akoNS/avi-secret update or delete
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/ingress_model_rel.go
  pkg/utils/utils.go
Labels: cherry-pick-required, cla-not-required

#198 l7 pool name fix for nested paths
  internal/lib/lib.go
Labels: cherry-pick, cla-not-required

#199 Fetching kube config file path
  tests/scaletest/configs/st_testbed.json
  tests/scaletest/lib/ingress.go
  tests/scaletest/lib/utils.go
  tests/scaletest/scale_test.go
Labels: cla-not-required

#201 build AKO and run unit tests in containers
  Makefile
Labels: cla-not-required

#200 Integration Test Cases for syncing k8s namespaced ingresses
  Makefile
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/lib.go
  tests/integrationtest/lib.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
Labels: cla-not-required

#204 freeze controller api version to 20.1.2 for advancedl4
  internal/cache/avi_ctrl_clients.go
  internal/lib/constants.go
  internal/lib/lib.go
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required

#190 Set status in AKO statefulset on all avi object deletion
  helm/ako/templates/clusterrole.yaml
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/rest/dequeue_nodes.go
  internal/status/statefulset_status.go
Labels: cla-not-required

#206 Set status in AKO statefulset on all avi object deletion - part2
  helm/ako/templates/clusterrole.yaml
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/status/statefulset_status.go
Labels: cla-not-required

#207 cherry-pick commits from release-1.3.1 to master, conflict resolution
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/ingress_model_rel.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/utils.go
Labels: cla-not-required

#203 Openshift: Enable Namespace sync for routes
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/status/route_status.go
Labels: cla-not-required

#208 Fix: <oc describe route routename > crash
  internal/status/route_status.go
  tests/oshiftroutetests/oshift_route_rest_test.go
Labels: cla-not-required

#205 Adding UT for tenancy change in AKO.
  tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/l7_ingress_node_test.go
  tests/integrationtest/l7_ingress_rest_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#210 Process service type ClusterIP in full sync if AKO is not running in Adv L4 mode
  internal/k8s/ako_init.go
  internal/nodes/avi_model_l4_translator.go
  tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
  tests/integrationtest/l7_ingress_node_test.go
Labels: cla-not-required
