Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2020-09, with the labels that each got.

#77 Skip validation for the node network list if DISABLE_STATIC_ROUTE_SYNC is true.
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#78 Fixing the helm charts + Controller version discovery
  helm/ako/templates/configmap.yaml
  helm/ako/templates/deployment.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/lib.go
  internal/rest/dequeue_nodes.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/utils.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/integrationtest/lib.go
Labels: cherry-pick-required, cla-not-required

#82 Misc fixes
  cmd/ako-main/main.go
  go.mod
  go.sum
  helm/ako/templates/configmap.yaml
  helm/ako/templates/deployment.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/rest/dequeue_nodes.go
  internal/retry/dequeue_retry.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/utils.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_route_model_test.go
  vendor/github.com/avinetworks/sdk/go/session/avisession.go
  vendor/modules.txt
Labels: cla-not-required

#81 additional fixes for status update
  internal/nodes/avi_model_l7_translator.go
  internal/rest/avi_obj_vs.go
  internal/rest/k8s_utils.go
  internal/status/ing_status.go
  internal/status/route_status.go
  tests/integrationtest/l7_ingress_rest_test.go
  tests/oshiftroutetests/oshift_route_rest_test.go
Labels: cherry-pick-required, cla-not-required

#83 New SDK pull plus delete fixes
  go.mod
  go.sum
  internal/lib/constants.go
  internal/rest/dequeue_nodes.go
  pkg/utils/avi_rest_utils.go
  vendor/github.com/avinetworks/sdk/go/session/avisession.go
  vendor/modules.txt
Labels: cla-not-required

#86 Stop the slow retry queue on sigterm
  internal/k8s/ako_init.go
Labels: cla-not-required

#84 additional fixes for status update
  internal/nodes/avi_model_l7_translator.go
  internal/rest/avi_obj_vs.go
  internal/rest/k8s_utils.go
  internal/status/ing_status.go
  internal/status/route_status.go
  tests/integrationtest/l7_ingress_rest_test.go
  tests/oshiftroutetests/oshift_route_rest_test.go
Labels: cla-not-required

#85 Misc fixes
  cmd/ako-main/main.go
  go.mod
  go.sum
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/rest/dequeue_nodes.go
  internal/retry/dequeue_retry.go
  pkg/utils/avi_rest_utils.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_service_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  vendor/github.com/avinetworks/sdk/go/session/avisession.go
  vendor/modules.txt
Labels: cherry-pick

#89 moving ako from deployment to statefulset
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/lib/constants.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#87 Changes to use ipamdnsproviderprofiledomainlist which will make fetching the subdomain generic wrt dns provider type.
  Makefile
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  tests/avimockobjects/ipamdnsproviderprofiledomainlist_mock.json
  tests/bootuptests/bootupmock/ipamdnsproviderprofiledomainlist_mock.json
  tests/integrationtest/lib.go
Labels: cherry-pick-required, cla-not-required

#92 moving ako from deployment to statefulset
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/lib/constants.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#93 changes in helm templates
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
Labels: cla-not-required

#91 Allow session version to be set during rest operate calls to Avi
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required

#95 Allow session version to be set during rest operate calls to Avi
  pkg/utils/avi_rest_utils.go
Labels: cherry-pick, cla-not-required

#94 changes in helm templates
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
Labels: cla-not-required

#96 skipping retry for dummy VS for stale object deletion
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#97 skipping retry for dummy VS for stale object deletion
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#90 Verify server rootCA chain verification in AKO
  go.sum
  helm/ako/templates/secret.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  pkg/utils/avi_rest_utils.go
  tests/hostnameshardtests/crd_hostname_test.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
Labels: cla-not-required

#98 Got rid of the SDK logs
  cmd/ako-main/main.go
Labels: cla-not-required

#99 populate pool from all PGs in vs cache during boot up
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#100 populate pool from all PGs in http policy and service pool select during boot up
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#101 populate pool from all PGs in vs cache during boot up
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#102 Validating NodeNetworkMap only if supplied, skipping the validation if empty.
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#104 Changes related to advanced L4
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/cni.go
  internal/lib/constants.go
  internal/lib/lib.go
Labels: cla-not-required

#105 advl4 gateway fixes for no backend svcs, static IP flow with new env vars, UTs
  internal/nodes/dequeue_ingestion.go
  internal/nodes/validator.go
  internal/rest/avi_obj_vs.go
  internal/status/advl4_status.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required

#106 Do not delete vsvip cache for insecure passthrough VS deletion
  internal/lib/lib.go
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  tests/oshiftroutetests/oshift_route_model_test.go
Labels: cla-not-required

#108 Do not delete vsvip cache for insecure passthrough VS deletion
  internal/lib/lib.go
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  tests/oshiftroutetests/oshift_route_model_test.go
Labels: cla-not-required

#107 Modifications to clusterID and ignore pool reachability
  internal/lib/lib.go
  internal/rest/avi_obj_vs.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required

#110 changed log file permission to enable edit by other users
  pkg/utils/log.go
Labels: cla-not-required

#111 changed log file permission to enable edit by other users
  pkg/utils/log.go
Labels: cla-not-required

#112 RemoveListeningPortOnVsDown only for L4 VSes
  internal/rest/avi_obj_vs.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
Labels: cla-not-required

#114 Disable informers and updates to kubebuilder annotation for gwclass
  internal/k8s/controller.go
  internal/lib/lib.go
Labels: cla-not-required

#115 Multiples Fixes: log file name and sni vs deletion error handling
  internal/rest/dequeue_nodes.go
  pkg/utils/log.go
Labels: cla-not-required

#116 multiple fixes: cherry-pick
  internal/rest/dequeue_nodes.go
  pkg/utils/log.go
Labels: cla-not-required

#113 RemoveListeningPortOnVsDown only for L4 VSes
  internal/rest/avi_obj_vs.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
Labels: cla-not-required

#109 service_api fixes, remove invalidAddress condition, sanitised gateway status condition reasons
  internal/k8s/advl4_controller.go
  internal/lib/cni.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/objects/services_apis.go
  internal/rest/avi_obj_vs.go
  internal/status/advl4_status.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
Labels: cla-not-required

#117 Allow AKO to work in psp enabled environments
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/psppolicy.yaml
  helm/ako/values.yaml
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
Labels: cla-not-required

#119 Bring the VS passthrough secure VS down on pool down
  internal/lib/constants.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#120 fix for passthrough vs name check in AviVsBuild
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#122 UTs for gateway/svc workflows, fixes
  internal/nodes/avi_model_advl4_translator.go
  internal/status/advl4_status.go
  tests/advl4tests/advl4_hostname_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#121 Bring the VS passthrough secure VS down on pool down
  internal/lib/constants.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#123 static IP on vsvip rest layer changes and gw status updates
  internal/k8s/advl4_controller.go
  internal/lib/constants.go
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  internal/status/advl4_status.go
  pkg/utils/types.go
Labels: cla-not-required

#103 wrap avi client inits in goroutines for faster bootup
  internal/cache/avi_ctrl_clients.go
  internal/k8s/ako_init.go
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required

#118 Allow AKO to work in psp enabled environments
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/psppolicy.yaml
  helm/ako/values.yaml
  internal/rest/avi_obj_vs.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
Labels: cla-not-required

#124 Use default-group for SEG if not specified.
  internal/lib/constants.go
  internal/lib/lib.go
Labels: cla-not-required

#125 Avoid unnecessary PUT calls to the Avi controller for Vsvip updates
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/ingress_model_rel.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#127 release-1.3.1 Branch Creation
  version.yaml
Labels: cla-not-required

#126 advl4 multi-gateway service swap UT
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required

#128 Setting base build number to 9000 for release-1.3.1
  base_build_num
Labels: cla-not-required

#129 cherrypick: advl4 multigateway service swap UT
  tests/advl4tests/advl4_hostname_test.go
Labels: cherry-pick, cla-not-required

#130 multi service cache map and address status fix
  internal/nodes/ingress_model_rel.go
  internal/status/advl4_status.go
  internal/status/svc_status.go
Labels: cla-not-required

#131 cherrypick: multi service cache map and address status fix
  internal/nodes/ingress_model_rel.go
  internal/status/advl4_status.go
  internal/status/svc_status.go
Labels: cherry-pick, cla-not-required

#133 Don't reset status if it's already reset.
  internal/status/svc_status.go
Labels: cherry-pick-required, cla-not-required

#134 changes in retry logic
  internal/rest/avi_datascript.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#136 Don't reset status if it's already reset.
  internal/status/svc_status.go
  tests/integrationtest/l7_ingress_rest_test.go
Labels: cherry-pick

#138 Use ldflags to print AKO version
  Dockerfile.ako
  Makefile
  cmd/ako-main/main.go
Labels: cla-not-required

#137 changes in retry logic
  internal/rest/avi_datascript.go
  internal/rest/dequeue_nodes.go
Labels: cherry-pick, cla-not-required

#141 Patch status for service_apis, gw status equality check, fixes
  internal/k8s/advl4_controller.go
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  internal/status/advl4_status.go
  internal/status/svc_status.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required
