Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2020-10, with the labels that each got.

#140 Disable full sync in advanced l4.
  internal/k8s/ako_init.go
Labels: cla-not-required

#132 Changing CONTRIBUTING file to point to latest AKO repo.
  CONTRIBUTING.md
  Dockerfile.ako
  helm/ako/templates/statefulset.yaml
  scripts/pre_stop_hook.sh
Labels: cla-not-required

#143 bulk gateway status updates, listener condition type fixes
  internal/cache/controller_obj_cache.go
  internal/k8s/advl4_controller.go
  internal/k8s/ako_init.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
Labels: cherry-pick-required, cla-not-required

#142 shutdown api server if configmap is deleted
  internal/k8s/ako_init.go
Labels: cla-not-required

#144 gw/svc status update improvements, log changes, endpoint UTs
  internal/cache/controller_obj_cache.go
  internal/rest/dequeue_nodes.go
  internal/status/advl4_status.go
  internal/status/svc_status.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cherry-pick-required, cla-not-required

#145 AKO release-1.3.1 cherry picks, status update fixes for sservices apis
  internal/cache/controller_obj_cache.go
  internal/k8s/advl4_controller.go
  internal/k8s/ako_init.go
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/svc_status.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required, in-progress

#148 Run full sync that syncs the gateway status with the service status
  go.sum
  internal/k8s/ako_init.go
Labels: cla-not-required

#149 remove redundant service status updates on event handlers
  internal/k8s/advl4_controller.go
  internal/status/advl4_status.go
  internal/status/svc_status.go
Labels: cla-not-required

#150 use patch call to update status for ingress and route
  internal/status/ing_status.go
  internal/status/route_status.go
Labels: cla-not-required

#147 Do fast retry only for 401 error
  internal/rest/dequeue_nodes.go
  vendor/github.com/avinetworks/sdk/go/session/avisession.go
Labels: cherry-pick-required, cla-not-required

#146 Optimising the processing of services during node CUD for NodePort mode.
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
Labels: cla-not-required

#151 AKO Stability Fix for invalid clustername
  CONTRIBUTING.md
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/lib.go
  scripts/pre_stop_hook.sh
Labels: cla-not-required

#153 adding retry for vsvip build failure
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/types.go
Labels: cla-not-required

#152 Run full sync that syncs the gateway status with the service status (…
  go.sum
  internal/k8s/ako_init.go
Labels: cla-not-required

#154 Cherry-picks: Do fast retry only for 401 error, adding retry for vsvip build failure
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/types.go
  vendor/github.com/avinetworks/sdk/go/session/avisession.go
Labels: cherry-pick, cla-not-required

#155 AKO-Stability-issue:
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/lib.go
Labels: cherry-pick, cla-not-required

#156 master to release-1.3.1 missing commits
  CONTRIBUTING.md
  internal/k8s/ako_init.go
Labels: cla-not-required

#139 Use ldflags to print AKO version
  Dockerfile.ako
  Makefile
  cmd/ako-main/main.go
Labels: cla-not-required

#157 cherry-pick missing release-1.3.1 commits in master
  internal/cache/controller_obj_cache.go
  internal/k8s/advl4_controller.go
  internal/status/advl4_status.go
  internal/status/svc_status.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required

#158 env var name change CTRL_CA_DATA
  helm/ako/templates/statefulset.yaml
  pkg/utils/avi_rest_utils.go
Labels: cherry-pick-required, cla-not-required

#159 cherrypick: env var name change CTRL_CA_DATA
  helm/ako/templates/statefulset.yaml
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required

#160 Shutdown API Server if Avi Controller password is changed
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#162 Shutdown API Server if Avi Controller password is changed
  internal/rest/dequeue_nodes.go
Labels: cherry-pick, cla-not-required

#161 gateway finalizers implementation
  internal/lib/advl4.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/status/advl4_status.go
Labels: cherry-pick-required, cla-not-required

#164 catch intended gateway delete via deletionTimestamp
  go.mod
  internal/k8s/advl4_controller.go
  internal/nodes/dequeue_ingestion.go
Labels: cherry-pick-required, cla-not-required

#163 Allowing public clouds in Cluster IP mode.
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  tests/multicloudtests/multi_cloud_test.go
Labels: cla-not-required

#167 Increase informer re-sync value and reduction of configmap informer cache
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  pkg/utils/types.go
  pkg/utils/utils.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cherry-pick

#166 Increase informer re-sync value and reduction of configmap informer cache
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  pkg/utils/types.go
  pkg/utils/utils.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required

#168 persist VS in avi for broken gw-svc relationship if gateway is valid
  internal/nodes/dequeue_ingestion.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cherry-pick-required, cla-not-required

#170 cherrypicks from release-1.3.1
  go.mod
  helm/ako/templates/secret.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/k8s/advl4_controller.go
  internal/lib/advl4.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/dequeue_ingestion.go
  internal/status/advl4_status.go
  tests/advl4tests/advl4_hostname_test.go
Labels: cherry-pick, cla-not-required

#171 change secret field from rootCA to certificateAuthorityData
  helm/ako/templates/secret.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
Labels: cherry-pick-required, cla-not-required

#169 Don't brick Avi VSes if kube API server is flakey
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  pkg/utils/full_sync_worker.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
  tests/integrationtest/l4_service_test.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
Labels: cla-not-required

#174 Don't brick Avi VSes if kube API server is flakey
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  pkg/utils/full_sync_worker.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
  tests/integrationtest/l4_service_test.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
Labels: cherry-pick, cla-not-required

#177 Allow System-TCP-Fast-Path only as the network profile for adv l4
  internal/nodes/avi_model_advl4_translator.go
  pkg/utils/constants.go
Labels: cherry-pick

#176 Allow System-TCP-Fast-Path only as the network profile for adv l4
  internal/nodes/avi_model_advl4_translator.go
  pkg/utils/constants.go
Labels: cla-not-required

#165 Scale Test Suite for AKO
  Makefile
  tests/scaletest/configs/st_testbed.json
  tests/scaletest/ingress_scale_test.go
  tests/scaletest/lib/ingress.go
  tests/scaletest/lib/parser.go
  tests/scaletest/lib/utils.go
  tests/scaletest/scale_test.go
Labels: cla-not-required
