Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-07, with the labels that each got.

#481 skip AviInfraSetting network presence check for Azure Cloud
  internal/k8s/crdcontroller.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
Labels: cla-not-required

#483 Remove unused port 80 being exposed by ako pod via statefulset
  helm/ako/templates/statefulset.yaml
  helm/ako/templates/tests/test-connection.yaml
  helm/ako/values.yaml
Labels: cla-not-required

#486 Allow vipNetworkList to be empty in case of advancedL4
  internal/k8s/controller.go
  internal/lib/lib.go
Labels: cla-not-required

#490 add name in fake API responses if not present
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#485 Retry rest operations if avi controller upgrade is in progress
  internal/lib/constants.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
Labels: cla-not-required

#489 Scale Test Coverage - Check if all VSes are UP
  tests/scaletest/configs/st_testbed.json
  tests/scaletest/lib/ingress.go
  tests/scaletest/lib/parser.go
  tests/scaletest/lib/utils.go
  tests/scaletest/scale_test.go
Labels: cla-not-required

#491 Fix problem with default secret annotation in Ingress
  internal/nodes/validator.go
  tests/advl4tests/advl4_hostname_test.go
  tests/ingresstests/ingress_annotation_test.go
  tests/ingresstests/ingressclass_test.go
Labels: cla-not-required

#471 Adding length check for AVI objects
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/ssl_key_certificate.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_rest_test.go
Labels: cla-not-required

#492 Refactor vipNetworkList to include CIDR
  Makefile
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  go.sum
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  pkg/apis/ako/v1alpha1/aviinfrasetting.go
  pkg/apis/ako/v1alpha1/zz_generated.deepcopy.go
  tests/ingresstests/ingressclass_test.go
  tests/integrationtest/l4_nodeport_service_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/npltests/npl_pod_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#494 adding additional logs for raw avi api queries outside rest layer
  internal/cache/controller_obj_cache.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/lib/avi_api.go
Labels: cherry-pick-required, cla-not-required

#496 adding additional logs for raw avi api queries outside rest layer
  internal/cache/controller_obj_cache.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/lib/avi_api.go
Labels: cherry-pick, cla-not-required

#500 skip serviceLB status updates during bootup for layer7Only usecases
  internal/rest/k8s_utils.go
  internal/status/svc_status.go
Labels: cla-not-required

#501 skip serviceLB status updates during bootup for layer7Only usecases
  internal/rest/k8s_utils.go
  internal/status/svc_status.go
Labels: cherry-pick, cla-not-required

#498 Fix EVH L4 service deletion
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#502 migrate AKO docs and changelog from avi-helm-charts repository
  CHANGELOG.md
  README.md
  docs/README.md
  docs/ako_evh.md
  docs/ako_operator.md
  docs/ako_tenancy.md
  docs/akoconfig.md
  docs/crds/avinfrasetting.md
  docs/crds/hostrule.md
  docs/crds/httprule.md
  docs/crds/overview.md
  docs/data_path_flow.png
  docs/faq.md
  docs/gateway-api/gateway-api.md
  docs/images/avi_tenants_and_roles.png
  docs/images/new_tenant.png
  docs/images/new_user.png
  docs/images/new_user_role.png
  docs/images/public_cloud/azure_routing.png
  docs/images/public_cloud/gcp_routing.png
  docs/images/public_cloud/gcp_segroup.png
  docs/images/public_cloud/gke_networking.png
  docs/images/public_cloud/inband.png
  docs/images/public_cloud/two_arm.png
  docs/images/role_list.png
  docs/images/tenant_path.png
  docs/images/user_path.png
  docs/ingress/ingress.md
  docs/install/helm.md
  docs/install/operator.md
  docs/objects.md
  docs/openshift/objects.md
  docs/openshift/openshift.md
  docs/public_clouds.md
  docs/roles/ako-admin.json
  docs/roles/ako-essential.json
  docs/roles/ako-tenant.json
  docs/roles/avicontroller-ako.json
  docs/troubleshooting.md
  docs/values.md
Labels: cla-not-required

#505 file name fixes, broken link fixes in AKO docs
  ako_arch.png
  docs/README.md
  docs/ako_operator.md
  docs/crds/overview.md
  docs/install/operator.md
Labels: cla-not-required

#504 Fix Adv L4 object names: Do not encode object names in Advance L4 deployment
  internal/lib/lib.go
Labels: cla-not-required

#495 Scale Test - Test case to check for any redundant/unwanted API calls to AVI on AKO reboot
  tests/scaletest/lib/ingress.go
  tests/scaletest/lib/utils.go
  tests/scaletest/scale_test.go
  vendor/github.com/avinetworks/sdk/go/models/event_log.go
Labels: cla-not-required

#509 Fix multihost ingress status update during bootup
  internal/status/route_status.go
Labels: cherry-pick-required

#510 use clientset while validating ingress class during status sync
  internal/lib/lib.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
Labels: cherry-pick-required, cla-not-required

#511 chery-picks from release-1.4.3 bug fixes related to status syncing
  internal/lib/lib.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/status/route_status.go
Labels: cherry-pick, cla-not-required

#503 Add overrides for networkprofiles for services with different protocols
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  cmd/ako-main/main.go
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/k8s/controller.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/dequeue_nodes.go
  internal/status/svc_status.go
  pkg/utils/constants.go
  pkg/utils/utils.go
  tests/ingresstests/l7_nodeport_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#514 Update the version to 1.4.3 for release-1.4.3
  version.yaml
Labels: cla-not-required

#513 Disable static route syncs for NSX-T cloud
  helm/ako/values.yaml
  internal/lib/constants.go
  internal/lib/lib.go
Labels: cla-not-required

#497 EVH: Remove namespace field from child VS name
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_rest_test.go
Labels: cla-not-required

#512 Allow specifying hostname per gateway listener
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/k8s_utils.go
  internal/status/svcapi_status.go
  tests/advl4tests/advl4_hostname_test.go
  tests/ingresstests/ingressclass_test.go
  tests/oshiftroutetests/oshift_secure_route_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#515 Skip updating vs uuid in annotation for insecureedgeallow
  internal/cache/cache_utils.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/validator.go
  internal/status/route_status.go
Labels: cla-not-required

#516 Skip updating vs uuid in annotation for insecureedgeallow
  internal/cache/cache_utils.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/validator.go
  internal/status/route_status.go
Labels: cherry-pick

#517 Regression issue fix for multi host ingresses with different IPs.
  internal/status/route_status.go
Labels: cla-not-required

#506 Configure static routes inside T1 VRFs
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#519 Regression issue fix for multi host ingresses with different IPs. (cherry-pick)
  internal/status/route_status.go
Labels: cherry-pick, cla-not-required

#518 Calculate graph checksum using all nested nodes' checksums
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  tests/ingresstests/l7_graph_test.go
  tests/integrationtest/l4_service_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#521 Support for multi-port services with port number
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/validator.go
  tests/ingresstests/l7_graph_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#520 A few miscellaneous fixes and updates to docs/tests/utility functions.
  README.md
  docs/README.md
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  tests/ingresstests/ingress_annotation_test.go
  tests/ingresstests/ingressclass_test.go
Labels: cla-not-required

#522 Ignore 404 error for DELETE operations
  internal/rest/rest_operation.go
Labels: cla-not-required

#493 Add public ip support for public cloud
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_obj_vsvip.go
  pkg/apis/ako/v1alpha1/aviinfrasetting.go
  tests/ingresstests/ingressclass_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required
