Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-03, with the labels that each got.

#275 AKO Operator changes
  ako-operator/README.md
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/config/secrets/secret.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
Labels: cla-not-required

#285 Delete servers from model when Service is deleted for NPL
  internal/nodes/ingress_model_rel.go
  tests/integrationtest/lib.go
  tests/npltests/npl_pod_test.go
Labels: cla-not-required

#286 cherry-pick: fix ingressclass template for defaultIngController
  helm/ako/templates/ingressclass.yaml
Labels: cherry-pick, cla-not-required

#287 cherry-pick: fix ingressclass template for defaultIngController
  helm/ako/templates/ingressclass.yaml
Labels: cla-not-required

#289 Fix problem in deleting NPL annotation from Service
  internal/nodes/dequeue_ingestion.go
  internal/objects/npl.go
  internal/status/svc_annotation.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
Labels: cla-not-required

#281 Update vs uuids in the object annotations
  helm/ako/templates/clusterrole.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/services_api_status.go
  internal/status/svc_status.go
Labels: cla-not-required

#291 Provide NetworkName via AviVsVipNode graph layer consistently
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_obj_vsvip.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#293 UTs and fixes for annotation based AviInfraSetting usage in Service LB
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_crd_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#295 Updated version files for new branch
  Dockerfile.ako
  Dockerfile.ako-operator
  Makefile
  version.yaml
Labels: cla-not-required

#294 Allow AKO to function as a pure layer 7 ingress controller
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/lib/utils.go
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#288 Graph and Rest layer changes for supporting EVH in AKO.
  Makefile
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#292 L4 Namespace Sync
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/utils.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/dequeue_ingestion.go
  internal/status/ing_status.go
  internal/status/route_status.go
  pkg/utils/constants.go
  pkg/utils/utils.go
Labels: cla-not-required

#300 rename selector keys for gateway to service mapping, non-advl4 workflow
  internal/k8s/services_api.go
  internal/lib/constants.go
  internal/nodes/ingress_model_rel.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#301 Update the AKOConfig object with layer7only flag
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/controllers/utils.go
Labels: cla-not-required

#299 Update NPL annotation in Service based on Ingress Class
  internal/nodes/ingress_model_rel.go
  tests/integrationtest/lib.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_crd_test.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
Labels: cla-not-required

#298 Introduce dedicated VS for ingress FQDNs
  helm/ako/values.yaml
  internal/cache/avi_ctrl_clients.go
  internal/k8s/ako_init.go
  internal/lib/lib.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/dequeue_nodes.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#302 cleanup test namespace in oshiftroutetests
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
  tests/oshiftroutetests/oshift_secure_route_test.go
Labels: cla-not-required

#290 fix default ingressclass transitioning issues
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  internal/nodes/ingress_model_rel.go
  internal/status/ing_status.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/crd_hostname_test.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
  tests/integrationtest/ingressclass_test.go
  tests/integrationtest/l7_ingress_node_test.go
  tests/integrationtest/l7_ingress_rest_test.go
Labels: cla-not-required

#303 Introduce GSLB FQDN in HostRule CRD
  helm/ako/crds/ako.vmware.com_hostrules.yaml
  internal/apis/ako/v1alpha1/hostrule.go
  internal/apis/ako/v1alpha1/zz_generated.deepcopy.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/validator.go
  internal/rest/avi_obj_httpps.go
  tests/hostnameshardtests/crd_hostname_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#277 Adding vipNetworkList to config for multivip support
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_obj_vsvip.go
  tests/integrationtest/l4_service_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#304 AviInfraSetting integration with IngressClass and Routes
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  internal/apis/ako/v1alpha1/aviinfrasetting.go
  internal/apis/ako/v1alpha1/zz_generated.deepcopy.go
  internal/k8s/services_api.go
  internal/lib/constants.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/crd_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#307 Fixing the ApplicationProfile and associating the redirect policy for EVH child VS.
  internal/nodes/avi_model_evh_nodes.go
  internal/rest/avi_evh_obj.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_test.go
Labels: cla-not-required

#311 deprecate namespace shard scheme
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/validator.go
  internal/rest/avi_obj_vs.go
  pkg/utils/avi_obj_cache.go
  tests/hostnameshardtests/l7_hostname_shard_nodeport_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/ingressclass_test.go
  tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
  tests/integrationtest/l4_nodeport_test.go
  tests/integrationtest/l7_ingress_node_test.go
  tests/integrationtest/l7_ingress_rest_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
Labels: cla-not-required

#312 remove shardingScheme from AKOConfig
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/suite_test.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
Labels: cla-not-required

#308 L4 Namespace Sync for GatewayAPI/ServiceAPI services
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/services_api.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/validator.go
  pkg/utils/utils.go
Labels: cla-not-required

#310 Temporary support for http caching via pools
  Makefile
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/rest/avi_obj_httpps.go
  internal/rest/dequeue_nodes.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#314 skip status deletion for Ingress if hostname is present in spec
  internal/lib/lib.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/ingress_model_rel.go
  internal/status/ing_status.go
  internal/status/route_status.go
Labels: cla-not-required

#315 skip status deletion for Ingress if hostname is present in spec
  Dockerfile.ako
  Dockerfile.ako-operator
  internal/lib/lib.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/ingress_model_rel.go
  internal/status/ing_status.go
  internal/status/route_status.go
  version.yaml
Labels: cla-not-required

#319 Do not delete FQDN-vsuuid map from ingress annotation if host is present in ingress
  internal/status/ing_status.go
  internal/status/route_status.go
Labels: cla-not-required

#305 Handle error in rest layer to sync requests from multiple K8s objects
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
  internal/rest/rest_utils.go
  internal/rest/ssl_key_certificate.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
Labels: cherry-pick-required, cla-not-required

#322 Fix GSLB Fqdn mapping for routes
  internal/nodes/validator.go
Labels: cla-not-required

#323 Fix GSLB Fqdn mapping for routes
  internal/nodes/validator.go
Labels: cla-not-required

#317 configure applicationPersistenceProfile via HttpRule
  ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
  helm/ako/crds/ako.vmware.com_httprules.yaml
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/rest/avi_obj_pool.go
  pkg/apis/ako/v1alpha1/httprule.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick-required, cla-not-required

#324 cherry-pick: configure applicationPersistenceProfile via HttpRule
  ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
  helm/ako/crds/ako.vmware.com_httprules.yaml
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/rest/avi_obj_pool.go
  pkg/apis/ako/v1alpha1/httprule.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick, cla-not-required

#321 Do not delete FQDN-vsuuid map from ingress annotation if host is present in ingress
  internal/status/ing_status.go
  internal/status/route_status.go
Labels: cla-not-required

#325 cherry-pick, Modifying the pool name to include the service name for consistent naming in kubernetes and openshift use cases.
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_test.go
Labels: cla-not-required

#318 Modifying the pool name to include the service name for consistent naming in kubernetes and openshift use cases.
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_test.go
Labels: cherry-pick-required, cla-not-required

#326 Handle error in rest layer to sync requests from multiple K8s objects
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
  internal/rest/rest_utils.go
  internal/rest/ssl_key_certificate.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
Labels: cherry-pick, cla-not-required

#320 Introduce GSLB host header re-write for insecure hosts
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
  pkg/utils/constants.go
  tests/hostnameshardtests/crd_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/integrationtest/lib.go
Labels: cherry-pick-required, cla-not-required

#330 Cherry-pick changes to release-1.4.1
  internal/nodes/avi_model_l7_translator.go
  internal/rest/rest_operation.go
  tests/oshiftroutetests/oshift_secure_route_test.go
Labels: cherry-pick, cla-not-required

#329 Introduce GSLB host header re-write for insecure hosts
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
  pkg/utils/constants.go
  tests/hostnameshardtests/crd_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/integrationtest/lib.go
Labels: cherry-pick, cla-not-required
