Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-05, with the labels that each got.

#422 fix for checking cloud type in GetVipNetworkList
  internal/lib/lib.go
Labels: cherry-pick, cla-not-required

#424 Process SwitchingAction in http policy rule only if it contains SwitchingAction
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#423 Removing default pool group reference from EVH Child.
  internal/rest/avi_evh_obj.go
Labels: cla-not-required

#425 Fix to set ServiceEngineGroup for the EVH VS's
  internal/nodes/avi_model_evh_nodes.go
Labels: cherry-pick, cla-not-required

#431 keep EnableRhi nil if not set to true
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#426 Add/Remove HTTP redirect rules for gslb fqdn
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/objects/crdrules.go
Labels: cla-not-required

#433 Use index while accessing network from networkList in rest layer for AWS multiVip
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required

#434 Allow listening to endpoint updates in NodePort mode
  internal/k8s/controller.go
Labels: cla-not-required

#436 Slow retry forever on error - No available free IPs
  Makefile
  internal/lib/constants.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
  tests/advl4tests/advl4_hostname_test.go
  tests/oshiftroutetests/oshift_route_passthrough_test.go
Labels: cla-not-required, do-not-merge

#437 Modified version yaml master branch
  Dockerfile.ako
  Makefile
  ako-operator/Makefile
  version.yaml
Labels: cla-not-required

#439 Change the application of SSL related properties of hostrule from EVH child to parent Node.
  internal/nodes/avi_model_evh_nodes.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
Labels: cla-not-required

#440 Change the application of SSL related properties of hostrule from EVH child to parent Node.
  internal/nodes/avi_model_evh_nodes.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
Labels: cherry-pick, cla-not-required

#441 prevent service status removal even if status update has errors
  internal/status/ing_status.go
  internal/status/svc_status.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
Labels: cherry-pick-required, cla-not-required

#443 prevent service status removal even if status update has errors (#441)
  internal/status/ing_status.go
  internal/status/svc_status.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
Labels: cherry-pick, cla-not-required

#442 SyncObjectStatus status persistence tests for ingress/route/svcLB
  internal/lib/lib.go
  internal/status/ing_status.go
  internal/status/route_status.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_route_rest_test.go
Labels: cla-not-required

#451 Fixing Continuous POST calls for sslkeyandcertificate in 409 error and DELETE calls for other AVI objects in 404 error
  internal/rest/dequeue_nodes.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required

#448 Support for Passthough hosts in Ingress
  internal/lib/constants.go
  internal/nodes/validator.go
  tests/hostnameshardtests/ingress_annotation_test.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_route_rest_test.go
Labels: cla-not-required

#400 update virtualservice checksum based on ref names instead of ref checksums
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  tests/hostnameshardtests/crd_hostname_test.go
Labels: cla-not-required

#452 Supporting NPL in passthrough mode and bug fix
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  tests/hostnameshardtests/ingress_annotation_test.go
Labels: cla-not-required

#432 Introduce bgpPeerLabels to enable selection of BGP peers for vsvip advertisement
  Makefile
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/api/v1alpha1/zz_generated.deepcopy.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  ako-operator/helm/ako-operator/values.yaml
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/ingressclass.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/dequeue_ingestion.go
  internal/objects/infrasetting.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/dequeue_nodes.go
  pkg/apis/ako/v1alpha1/aviinfrasetting.go
  pkg/apis/ako/v1alpha1/zz_generated.deepcopy.go
  tests/advl4tests/advl4_hostname_test.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/ingress_annotation_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/l4_nodeport_service_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#458 fix configmap key reference for bgpPeerLabels
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  helm/ako/templates/statefulset.yaml
  tests/ingresstests/l7_graph_test.go
Labels: cla-not-required

#455 Move AviInfraSetting SEG checks before configuring labels
  internal/k8s/crdcontroller.go
Labels: cla-not-required
