Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-12, with the labels that each got.

#705 AV-131413: VS not getting converted to Dedicated VS Type using AVIInfraSetting CRD
  internal/k8s/controller.go
Labels: cla-not-required

#698 Adds testcase to scale test code
  tests/scaletest/lib/ingress.go
  tests/scaletest/scale_test.go
Labels: cla-not-required

#710 Reverts the code to skip the shared empty parent VS deletion
  internal/k8s/ako_init.go
Labels: cla-not-required

#704 AKO Operator: Cherry-picks from op-release 1.5.2
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/api/v1alpha1/zz_generated.deepcopy.go
  ako-operator/bundle.Dockerfile
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/clusterrole.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/manager/manager.yaml
  ako-operator/config/rbac/auth_proxy_role.yaml
  ako-operator/config/rbac/auth_proxy_role_binding.yaml
  ako-operator/config/rbac/kustomization.yaml
  ako-operator/config/rbac/role.yaml
  ako-operator/config/secrets/secret.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/crb.go
  ako-operator/controllers/crd.go
  ako-operator/controllers/psp.go
  ako-operator/controllers/role.go
  ako-operator/controllers/sa.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/values.yaml
  ako-operator/main.go
  go.mod
  go.sum
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/modules.txt
Labels: cla-not-required, cherry-pick

#702 Handling non admin tenant with SE_in_provider_context set
  ako-infra/ingestion/avi_infra_controller.go
  internal/cache/controller_obj_cache.go
  internal/lib/avi_api.go
  internal/lib/lib.go
Labels: cla-not-required

#713 Public IP and Status Update Fixes
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required

#709 Donot create dedicated VS if gateway labels are present on the service
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/dequeue_ingestion.go
  tests/evhtests/l7_evh_graph_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#717 Fix route status update while deleting entry from status
  internal/status/route_status.go
  tests/evhtests/l7_evh_graph_test.go
Labels: cla-not-required

#714 Introduce fqdnType (Exact/Contains/Wildcard) in HostRule
  ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
  helm/ako/crds/ako.vmware.com_hostrules.yaml
  internal/k8s/ako_init.go
  internal/k8s/crdcontroller.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/objects/crdrules.go
  internal/objects/store.go
  internal/status/route_status.go
  pkg/apis/ako/v1alpha1/hostrule.go
Labels: cla-not-required

#706 Support for multiple FQDNs in child VS
  Makefile
  ako-operator/controllers/crd.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
  helm/ako/crds/ako.vmware.com_hostrules.yaml
  internal/k8s/crdcontroller.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/crd_translator.go
  internal/objects/crdrules.go
  pkg/apis/ako/v1alpha1/hostrule.go
  pkg/apis/ako/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/types.go
  pkg/utils/utils.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
Labels: cla-not-required

#721 cherrypick: Donot create dedicated VS if gateway labels are present on the service
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/dequeue_ingestion.go
  pkg/utils/types.go
  tests/evhtests/l7_evh_graph_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#723 remove fqdnType as a required field for hostrules
  ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
  helm/ako/crds/ako.vmware.com_hostrules.yaml
Labels: cla-not-required

#718 Retain the shared VS VIP on ako reboot
  internal/cache/controller_obj_cache.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/dequeue_nodes.go
  tests/ingresstests/l7_rest_test.go
Labels: cla-not-required

#715 test cases for ako-infra boostrapconditions
  Makefile
  ako-infra/avirest/handle_netinfo.go
  ako-infra/ingestion/avi_infra_controller.go
  ako-infra/ingestion/vcf_k8s_controller.go
  internal/lib/dynamic_client.go
  tests/avimockobjects/CLOUD_NSXT_mock.json
  tests/infratests/akoinfra_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#712 Remove advanced_l4 from helm
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
Labels: cla-not-required

#707 Configure pool placement settings via AviInfraSetting CRDs
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/route_ingress_model.go
  internal/rest/avi_obj_pool.go
  pkg/apis/ako/v1alpha1/aviinfrasetting.go
  pkg/apis/ako/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/types.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
Labels: cla-not-required

#724 AKO CRD documentation and missing ako-operator install workflow
  ako-operator/controllers/crd.go
  docs/crds/avinfrasetting.md
  docs/crds/hostrule.md
Labels: cla-not-required

#716 Add SEG to dedicated VS. Remove FQDN in case of wrong certificate
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required

#722 Doc: Documentation for the new field aliases in hostrule CRD
  docs/crds/hostrule.md
  internal/k8s/crdcontroller.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
Labels: cla-not-required

#726 Patch the l4 policy rule name to be similar to the corresponding Pool name
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_obj_l4ps.go
Labels: cla-not-required, cherry-pick-required

#727 cherry-pick: Patch the l4 policy rule name to be similar to the corresponding Pool name
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_obj_l4ps.go
Labels: cla-not-required, cherry-pick

#729 Docs AKO events and hostrule tcpSettings
  docs/crds/hostrule.md
  docs/troubleshooting/events.md
  docs/troubleshooting/troubleshooting.md
  internal/nodes/avi_model_nodes.go
  internal/nodes/validator.go
Labels: cla-not-required

#728 Deprecating tenantsPerCluster flag
  ako-infra/ingestion/avi_infra_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/controllers/utils.go
  docs/akoconfig.md
  docs/install/helm.md
  docs/values.md
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/rest/avi_obj_vrf.go
Labels: cla-not-required

#725 Release 1.6.1- Update compatibility matrix doc
  buildsettings.json
  docs/README.md
Labels: cla-not-required

#720 AKO Operator 1.5.2 patch fixes
  ako-operator/Makefile
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/rbac/role.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/controllers/role.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
Labels: cla-not-required

#711 AKO Operator changes for 1.6.1
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/rbac/role.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/role.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
Labels: cla-not-required

#731 Chagelog for 1.6.1
  CHANGELOG.md
Labels: cla-not-required

#733 Fix: Retains the dns info corresponding to the parent FQDN
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#736 Dedicated VS documentation
  docs/ako_evh.md
  docs/objects.md
Labels: cla-not-required

#734 update clusterrole for statefulset annotation update
  helm/ako/templates/clusterrole.yaml
Labels: cla-not-required

#735 delete status from pool, while deleting child VS
  internal/nodes/dequeue_ingestion.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#730 Do not overwrite the ipam network subnet config in Vip before PUT
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/rest/avi_obj_vsvip.go
  internal/status/route_status.go
  tests/avimockobjects/CLOUD_NSXT_mock.json
  tests/avimockobjects/CLOUD_VCENTER_mock.json
  tests/avimockobjects/ipamdnsproviderprofile_uuid_mock.json
  tests/ingresstests/l7_graph_test.go
Labels: cla-not-required

#739 Docs Updated for AKO Tenancy Support
  docs/ako_tenancy.md
Labels: cla-not-required

#737 AKO 1.6.1- changes in helm upgrade process
  docs/install/helm.md
  docs/upgrade/upgrade.md
Labels: cla-not-required

#738 Doc: FAQ changes for `retain VS VIP over AKO reboot`
  CHANGELOG.md
  docs/faq.md
Labels: cla-not-required

#693 Make status update get/list calls using informer cache
  internal/k8s/ako_init.go
  internal/lib/lib.go
  internal/status/advl4_status.go
  internal/status/crd_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
  tests/oshiftroutetests/oshift_route_model_test.go
Labels: cla-not-required

#740 Doc update for AKO statefulset annotation change
  docs/faq.md
Labels: cla-not-required, cherry-pick-required

#742 Always recreate IPAMNetworkSubnet while updating VSVIP
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required, cherry-pick-required

#743 cherry-pick: Control AKO Event broadcasting using ConfigMap `enableEvents`
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/akoconfig.md
  docs/install/helm.md
  docs/install/operator.md
  docs/troubleshooting/events.md
  docs/values.md
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/control_config.go
  pkg/utils/events.go
Labels: cla-not-required, cherry-pick

#745 Status update push to queue fixes, ingress/svc/route update check enhancements
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
Labels: cla-not-required
