Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-09, with the labels that each got.

#606 Fix for marker based network name, additional logs
  internal/cache/controller_obj_cache.go
Labels: cherry-pick-required

#604 Support for kubernetes 1.22, with deprecated support for networkingv1beta1
  buildsettings.json
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/route_ingress_model.go
  internal/nodes/validator.go
  internal/status/ing_status.go
  pkg/utils/ingress.go
  pkg/utils/types.go
  pkg/utils/utils.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/ingress_annotation_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#608 Ensure AKO reboot on secret Add/Delete
  internal/k8s/controller.go
Labels: cla-not-required, cherry-pick-required

#597 Add warning when vipNetworkList is not provided via values.yaml
  internal/cache/controller_obj_cache.go
Labels: cla-not-required, cherry-pick

#610 WCP fixes 1.5.2 to master cherry-picks
  internal/cache/controller_obj_cache.go
  internal/k8s/controller.go
Labels: cla-not-required, cherry-pick

#613 Fix EVH and SNI: multiport service with portnumber specified in ingress definition
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  tests/evhtests/l7_evh_graph_test.go
Labels: cla-not-required

#609 AV-122809: EVH: Hostrule SSLcertkeyref fixes for secure/insecure ingress, routes
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/rest/avi_evh_obj.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
Labels: cla-not-required, cherry-pick-required

#607 Handling Bootstrap CRD for NCP to AKO communication
  cmd/ako-main/main.go
  internal/k8s/controller.go
  internal/k8s/vcf_controller.go
  internal/lib/dynamic_client.go
  internal/lib/lib.go
  tests/evhtests/l7_evh_ingressclass_test.go
Labels: cla-not-required

#616 Fix EVH and SNI: multiport service with portnumber specified in ingress definition
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  tests/evhtests/l7_evh_graph_test.go
Labels: cla-not-required, cherry-pick

#571 Public IP support and SAML Auth docs
  docs/crds/avinfrasetting.md
  docs/values.md
Labels: cla-not-required

#615 EVH & SNI: Hostrule SSLcertkeyref fixes for secure/insecure ingress, routes
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/rest/avi_evh_obj.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
Labels: cla-not-required, cherry-pick

#614 Make AKO bootups faster
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/objects/resourceversions.go
Labels: cla-not-required

#617 Fix HTTPRule setting on Pool for Route with no Path
  internal/nodes/crd_translator.go
Labels: cla-not-required

#619 Fix: Added missed 'authtoken' field
  ako-operator/helm/ako-operator/templates/secret.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/install/helm.md
  docs/install/operator.md
  helm/ako/values.yaml
Labels: cla-not-required

#621 Fix: Added missed 'authtoken' field
  ako-operator/helm/ako-operator/templates/secret.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/install/helm.md
  docs/install/operator.md
  helm/ako/values.yaml
Labels: cla-not-required, cherry-pick

#623 Fix HTTPRule setting on Pool for Route with no Path
  internal/nodes/crd_translator.go
Labels: cla-not-required, cherry-pick

#625 Make AKO bootups faster
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/objects/resourceversions.go
Labels: cla-not-required, release-1.5.2

#618 helm changes for VCF cluster and VIP per Namespace
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/validator.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/evhtests/l7_evh_rest_test.go
Labels: cla-not-required

#626 Status update should check for the AKO router name
  internal/status/route_status.go
  internal/status/svc_status.go
Labels: cla-not-required, cherry-pick-required

#622 Add AKO-Infra and reorganise files
  ako-infra/ingestion/controller.go
  ako-infra/ingestion/vcf_controller.go
  cmd/ako-main/main.go
  cmd/infra-main/main.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/dynamic_client.go
  internal/lib/lib.go
Labels: cla-not-required

#598 Introduce ability to record Events from AKO
  cmd/ako-main/main.go
  internal/cache/controller_obj_cache.go
  internal/k8s/advl4_controller.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/services_api.go
  internal/lib/advl4.go
  internal/lib/constants.go
  internal/lib/control_config.go
  internal/lib/crd.go
  internal/lib/lib.go
  internal/lib/servicesapi.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/crd_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/route_ingress_model.go
  internal/nodes/validator.go
  internal/rest/avi_obj_vsvip.go
  internal/status/advl4_status.go
  internal/status/crd_status.go
  internal/status/svcapi_status.go
  pkg/utils/events.go
  tests/advl4tests/advl4_hostname_test.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_crd_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#627 Status update should check for the AKO router name
  internal/status/route_status.go
  internal/status/svc_status.go
Labels: cla-not-required, cherry-pick

#629 Make the bootup cache population parallel
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/objects/avigraph.go
  internal/objects/store_lock less.go
  internal/objects/store_lock.go
Labels: cla-not-required, cherry-pick

#635 Publish the CRD if the status changes during bootup
  internal/k8s/crdcontroller.go
Labels: cla-not-required, cherry-pick-required

#636 Publish the CRD if the status changes during bootup
  internal/k8s/crdcontroller.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required, cherry-pick

#637 Added a change to convert the secret from clientset to informer
  internal/nodes/avi_model_l7_translator.go
Labels: cherry-pick

#639 Fix status update issue during WCP full sync
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
Labels: cla-not-required, cherry-pick-required

#638 Correct problem with status checks on CRD
  helm/ako/values.yaml
  internal/k8s/crdcontroller.go
  pkg/utils/utils.go
Labels: cla-not-required
