Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-06, with the labels that each got.

#462 add missing configmap map entry for building statefulset env vars
  ako-operator/controllers/utils.go
Labels: cla-not-required

#459 Fix for ako artifacts cleanup issue and a cherry-pick
  Dockerfile.ako-operator
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/controllers/utils.go
Labels: cla-not-required

#464 env variable AUTO_L4_FQDN ako-operator, Vsnode checksum update for autoFqdn fixes
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/utils.go
  internal/nodes/avi_model_nodes.go
  tests/ingresstests/ingressclass_test.go
Labels: cla-not-required

#463 Do not perform bulk status update on resources of un-accepted namespaces when namespace sync feature is enabled.
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
Labels: cla-not-required

#466 Fix for race conditons while updating avi model with for EVH
  internal/nodes/avi_model_evh_nodes.go
  tests/ingresstests/crd_test.go
  tests/npltests/npl_pod_test.go
Labels: cla-not-required

#467 Upgrade AKO Operator's SDK version to 3 from 3-alpha
  Dockerfile.ako-operator
  ako-operator/PROJECT
  ako-operator/config/default/kustomization.yaml
  ako-operator/config/manager/manager.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/utils.go
Labels: cla-not-required

#454 SAML auth for AKO using AVI authtoken
  cmd/ako-main/main.go
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/secret.yaml
  helm/ako/templates/statefulset.yaml
  internal/cache/avi_ctrl_clients.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/lib.go
  pkg/utils/avi_obj_cache.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/constants.go
  pkg/utils/utils.go
  tests/advl4tests/advl4_hostname_test.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/l7_graph_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#465 unblock AKO run if CRDs are not installed in cluster
  internal/k8s/controller.go
  internal/lib/crd.go
Labels: cherry-pick-required, cla-not-required

#468 Support for dynamic namespaces in AKO
  helm/ako/templates/statefulset.yaml
  internal/lib/constants.go
  internal/lib/lib.go
  pkg/utils/constants.go
  pkg/utils/utils.go
  tests/advl4tests/advl4_hostname_test.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/ingress_annotation_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/oshiftroutetests/oshift_route_namespace_sync_test.go
  tests/oshiftroutetests/oshift_secure_route_test.go
  tests/scaletest/scale_test.go
  tests/servicesapitests/servicesapi_l4_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cherry-pick-required, cla-not-required

#469 dynamic namespaces and AKO CRDs informer Run fixes
  Dockerfile.ako
  Makefile
  helm/ako/templates/statefulset.yaml
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/crd.go
  pkg/utils/constants.go
  pkg/utils/utils.go
  tests/advl4tests/advl4_hostname_test.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/oshiftroutetests/oshift_secure_route_test.go
  tests/scaletest/scale_test.go
  tests/servicesapitests/servicesapi_l4_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cherry-pick, cla-not-required

#470 Support NSX-T cloud in AKO
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required

#453 EVH: Encoding AVI object names
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/rest/avi_evh_obj.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_rest_test.go
Labels: cla-not-required

#472 add child node checksum to vs checksum calculation
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/dequeue_ingestion.go
  internal/status/route_status.go
  tests/oshiftroutetests/oshift_secure_route_test.go
Labels: cherry-pick-required, cla-not-required

#474 Retry for vsvip and vrf Get calls, replace with wrapper functions
  internal/lib/avi_api.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vsvip.go
  pkg/utils/avi_obj_cache.go
Labels: cla-not-required

#477 sync CRD files from ako helm directory to ako-operator
  Makefile
  ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
  internal/status/crd_status.go
Labels: cla-not-required

#479 Introduce buildsettings.json that enforces a supportability matrix
  Dockerfile.ako
  Makefile
  buildsettings.json
  cmd/ako-main/main.go
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
Labels: cla-not-required

#475 Openshift EVH changes
  Makefile
  internal/lib/constants.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/validator.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#478 Logging fixes and error handling
  cmd/ako-main/main.go
  internal/cache/avi_ctrl_clients.go
  internal/k8s/ako_init.go
  pkg/utils/avi_obj_cache.go
Labels: cla-not-required

#480 fix CRD patch calls to cast status object to CRD status objects
  internal/status/crd_status.go
Labels: cla-not-required

#484 Use VHDomainNames for VS checksum calculation
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_nodes.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/oshiftroutetests/oshift_route_namespace_sync_test.go
Labels: cla-not-required, regression

#482 Remove cache entry only when rest method is DELETE
  internal/nodes/avi_model_l7_translator.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required
