Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-04, with the labels that each got.

#316 Layer7 AviInfraSetting shardSize based modelName
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/route_ingress_model.go
  internal/objects/infrasetting.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/crd_hostname_test.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_test.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick-required, in-progress

#328 check error type for rest operation before handling error
  internal/rest/rest_operation.go
Labels: cherry-pick-required, cla-not-required

#331 cherry-pick: Layer7 AviInfraSetting shardSize based modelName (#316)
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/route_ingress_model.go
  internal/objects/infrasetting.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/crd_hostname_test.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
  tests/hostnameshardtests/l7_evh_hostnameshard_test.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick, cla-not-required

#334 Fixed some issues with existing unit tests.
  tests/hostnameshardtests/l7_hostname_shard_test.go
Labels: cla-not-required

#335 Fixed some issues with existing unit tests.
  tests/hostnameshardtests/l7_hostname_shard_test.go
Labels: cherry-pick, cla-not-required

#332 AviInfraSetting shardSize configuration for EVH VSes
  internal/k8s/ako_init.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/dequeue_ingestion.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick-required, cla-not-required

#333 Introduce skipnodeport annotation
  internal/lib/constants.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/crd_translator.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/integrationtest/l4_nodeport_test.go
  tests/integrationtest/lib.go
Labels: cherry-pick-required, cla-not-required

#338 Disable static routes when service type is set as NodePortLocal
  helm/ako/values.yaml
  internal/cache/.DS_Store
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  tests/npltests/npl_pod_test.go
Labels: cherry-pick-required, cla-not-required

#337 Check if AKO can access API of Service before checking Route API
  cmd/ako-main/main.go
  internal/lib/lib.go
Labels: cherry-pick-required, cla-not-required

#339 Move all CRD validations to the ingestion layer
  internal/k8s/crdcontroller.go
  internal/nodes/crd_translator.go
  internal/nodes/ingress_model_rel.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
Labels: cherry-pick-required, cla-not-required

#340 Disable static routes when service type is set as NodePortLocal
  helm/ako/values.yaml
  internal/cache/.DS_Store
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  tests/npltests/npl_pod_test.go
Labels: cherry-pick, cla-not-required

#342 Check if AKO can access API of Service before checking Route API
  cmd/ako-main/main.go
  internal/lib/lib.go
Labels: cherry-pick, cla-not-required

#336 update status of k8s objects through a queue
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/k8s_utils.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/status_toiler.go
  pkg/utils/constants.go
  pkg/utils/queue.go
  tests/advl4tests/advl4_hostname_test.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_service_test.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick-required, cla-not-required

#341 Introduce skipnodeport annotation
  internal/lib/constants.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/crd_translator.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/integrationtest/l4_nodeport_test.go
  tests/integrationtest/lib.go
Labels: cherry-pick, cla-not-required

#347 Move all CRD validations to the ingestion layer
  internal/k8s/crdcontroller.go
  internal/nodes/crd_translator.go
  internal/nodes/ingress_model_rel.go
  tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
Labels: cherry-pick, cla-not-required

#343 Logging improvement when serviceType is NodePortLocal
  internal/cache/.DS_Store
  internal/nodes/avi_model_l4_translator.go
Labels: cla-not-required

#345 update status of k8s objects through a queue
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/k8s_utils.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/status_toiler.go
  pkg/utils/constants.go
  pkg/utils/queue.go
  tests/advl4tests/advl4_hostname_test.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/hostnameshardtests/l7_hostname_rest_test.go
  tests/hostnameshardtests/l7_hostname_shard_test.go
  tests/integrationtest/l4_service_test.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick, cla-not-required

#349 Logging improvement when serviceType is NodePortLocal
  internal/cache/.DS_Store
  internal/nodes/avi_model_l4_translator.go
Labels: cherry-pick

#350 Improvement in adding NPL annotation for services
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/status/status_toiler.go
  internal/status/svc_annotation.go
  tests/npltests/npl_pod_test.go
Labels: cla-not-required

#351 adding missing fields to AKO config and ako-operator values.yaml
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
Labels: cherry-pick-required, cla-not-required

#353 delete NPL annotation from Services when deleteConfig is set to true
  internal/k8s/ako_init.go
Labels: cherry-pick-required, cla-not-required

#352 Improvement in adding NPL annotation for services
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/status/status_toiler.go
  internal/status/svc_annotation.go
  tests/npltests/npl_pod_test.go
Labels: cherry-pick, cla-not-required

#355 Provide a knob to switch off granular RBAC support
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
Labels: cherry-pick-required, cla-not-required

#356 Provide a knob to switch off granular RBAC support
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
Labels: cherry-pick, cla-not-required

#354 delete NPL annotation from Services when deleteConfig is set to true
  internal/k8s/ako_init.go
Labels: cherry-pick, cla-not-required

#358 Changing the make to execute many recipes simultaneously.
  Makefile
Labels: cla-not-required

#360 Cherry-picks from master branch to 1.4.1
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  tests/hostnameshardtests/crd_evh_hostname_test.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#363 fix vsvip checksum key
  internal/k8s/ako_init.go
  internal/objects/avigraph.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/dequeue_nodes.go
Labels: cherry-pick-required, cla-not-required

#364 cherrypick: fix vsvip checksum key
  internal/k8s/ako_init.go
  internal/objects/avigraph.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/dequeue_nodes.go
Labels: cherry-pick, cla-not-required

#362 Changes in rest layer to use Markers instead of Labels.
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required

#366 cherry-pick, Disable GRBAC if avi controller build is less than 20.1.5. (#362)
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
Labels: cherry-pick, cla-not-required

#368 disable setting global subnetIPPrefix for selective AviInfraSetting config
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_obj_vsvip.go
Labels: cherry-pick-required, cla-not-required

#348 Fixes for multivip with infrasetting
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/ingress_model_rel.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#370 Add session timeouts into retryable errors
  internal/rest/rest_operation.go
Labels: cla-not-required

#369 Fix issue related with ordering of httppolicysets of VS having same host with different Paths for Openshift route, K8 ingress
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_vs.go
Labels: cherry-pick-required, cla-not-required

#373 Add session timeouts into retryable errors
  internal/rest/rest_operation.go
Labels: cla-not-required

#374 cherry-pick: disable setting global subnetIPPrefix for selective AviInfraSetting config
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_obj_vsvip.go
Labels: cherry-pick, cla-not-required

#375 [Cherry-pick to 1.4.1] Fix issue related with ordering of httppolicysets of VS having same host with different Paths for Openshift route, K8 ingress (#369)
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#371 sslkeycert, pkiprofile, l4policy, vsdatascript layer 3 checksum without GRBAC fixes
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/ssl_key_certificate.go
Labels: cherry-pick-required, cla-not-required

#376 cherry-pick: sslkeycert, pkiprofile, l4policy, vsdatascript layer 3 checksum without GRBAC fixes
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required

#377 cherry-pick Fixes for multivip with infrasetting
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/ingress_model_rel.go
  tests/hostnameshardtests/ingressclass_hostname_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cherry-pick, cla-not-required

#378 prevent checksum overflow in VsDatascriptset
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
Labels: cherry-pick-required, cla-not-required

#379 prevent checksum overflow in VsDatascriptset
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
Labels: cherry-pick, cla-not-required

#380 crash fix: check for deleted object type DeletedFinalStateUnknown
  internal/k8s/advl4_controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/services_api.go
Labels: cherry-pick-required, cla-not-required

#381 cherry-pick: crash fix check for deleted object type DeletedFinalStateUnknown (#380)
  internal/k8s/advl4_controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/services_api.go
Labels: cherry-pick, cla-not-required

#382 fix status sync for status removal during reboot
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/lib/utils.go
  internal/rest/dequeue_nodes.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
Labels: cherry-pick-required, cla-not-required

#384 cherry-pick: fix status sync for status removal during reboot
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/lib/utils.go
  internal/rest/dequeue_nodes.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
Labels: cherry-pick, cla-not-required

#387 Remove SE group labels on deleteConfig
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
Labels: cla-not-required

#386 AKO operator changes for NPL
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/values.yaml
Labels: cherry-pick-required, cla-not-required

#385 Check AVI controller state during boot up
  cmd/ako-main/main.go
  internal/cache/controller_obj_cache.go
Labels: cherry-pick-required, cla-not-required

#388 remove AKO annotations completely from ingress/routes if present with stale values
  internal/status/ing_status.go
  internal/status/svc_status.go
Labels: cherry-pick-required, cla-not-required

#389 Cherry-pick changes to 1.4.1
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/values.yaml
  cmd/ako-main/main.go
  internal/cache/controller_obj_cache.go
Labels: cherry-pick, cla-not-required

#390 cherry-pick: remove AKO annotations completely from ingress/routes if present with stale values
  internal/status/ing_status.go
  internal/status/svc_status.go
Labels: cherry-pick, cla-not-required

#391 skip other operations if sni child deletion fails
  internal/rest/dequeue_nodes.go
Labels: cherry-pick-required, cla-not-required

#392 skip other operations if sni child deletion fails
  internal/rest/dequeue_nodes.go
Labels: cherry-pick, cla-not-required

#393 akoconfig YAML indentation fix
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
Labels: cherry-pick-required, cla-not-required

#394 fix YAML types for boolean and string array fields
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/api/v1alpha1/zz_generated.deepcopy.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/configmap.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
Labels: cherry-pick-required, cla-not-required

#396 propogate vsvip PUT errors to rest layer fix
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
  internal/rest/rest_utils.go
  internal/rest/ssl_key_certificate.go
Labels: cherry-pick-required, cla-not-required

#397 fix wrong script addition for checksum calculation
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
Labels: cherry-pick-required, cla-not-required

#398 cherry-pick: vsvip PUT error propogation, vsdatascriptset checksum fix
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
  internal/rest/rest_utils.go
  internal/rest/ssl_key_certificate.go
Labels: cherry-pick, cla-not-required

#399 Use correct index while deleting Ingress status
  internal/status/ing_status.go
Labels: cla-not-required

#401 Use correct index while deleting Route status
  internal/status/ing_status.go
  internal/status/route_status.go
Labels: cherry-pick-required, cla-not-required

#403 Cherry-pick: Use correct index while deleting Ingress/Route status
  internal/status/ing_status.go
  internal/status/route_status.go
Labels: cherry-pick, cla-not-required

#402 AKO Operator clusterrole change, Changing Update call to Patch in Reconcile
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/role.go
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
Labels: cla-not-required

#406 Cherry-pick: AKO Operator clusterrole change, Changing Update call to Patch in Reconcile
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/role.go
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
Labels: cla-not-required

#407 fix network assignment from AviInfraSetting, log fixes
  internal/k8s/crdcontroller.go
  internal/nodes/avi_model_l7_translator.go
  internal/rest/avi_obj_vsvip.go
Labels: cherry-pick-required, cla-not-required

#405 AKO operator changes for networkName to VipNetworkList migration
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/api/v1alpha1/zz_generated.deepcopy.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/suite_test.go
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
Labels: cla-not-required

#408 Fix for race conditons for updating avi model in graph layer
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
Labels: cherry-pick-required, cla-not-required

#409 Fix for race conditons for updating avi model in graph layer
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
Labels: cherry-pick, cla-not-required

#410 changing type of vip network from map to struct in operator
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/api/v1alpha1/zz_generated.deepcopy.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/utils.go
Labels: cherry-pick-required

#411 cherry-pick: fix network assignment from AviInfraSetting, log fixes
  internal/k8s/crdcontroller.go
  internal/nodes/avi_model_l7_translator.go
  internal/rest/avi_obj_vsvip.go
Labels: cherry-pick, cla-not-required

#412 AKO operator changes for networkName to VipNetworkList migration
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/api/v1alpha1/zz_generated.deepcopy.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
Labels: cherry-pick, cla-not-required

#413 AKO-1.4.1 cherry-picks: ako-operator updates and fixes
  ako-operator/controllers/configmap.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
Labels: cla-not-required

#415 Use kubeclient instead of informer to fetch ingress class for status update during bootup
  internal/lib/lib.go
  internal/status/ing_status.go
Labels: cherry-pick-required, cla-not-required

#416 match portname for multi port service while populating servers for NPL
  internal/nodes/avi_model_l4_translator.go
  tests/npltests/npl_pod_test.go
Labels: cherry-pick, cla-not-required

#417 Use kubeclient instead of informer to fetch ingress class for status update during bootup
  internal/lib/lib.go
  internal/status/ing_status.go
Labels: cherry-pick, cla-not-required

#414 match portname for multi port service while populating servers for NPL
  internal/nodes/avi_model_l4_translator.go
  tests/npltests/npl_pod_test.go
Labels: cherry-pick-required, cla-not-required

#418 check for vip network list after setting cloud type
  cmd/ako-main/main.go
Labels: cla-not-required

#419 Fix to set ServiceEngineGroup for the EVH VS's
  internal/nodes/avi_model_evh_nodes.go
Labels: cherry-pick-required, cla-not-required

#420 check for vip network list after setting cloud type
  cmd/ako-main/main.go
Labels: cherry-pick, cla-not-required

#421 fix for checking cloud type in GetVipNetworkList
  internal/lib/lib.go
Labels: cherry-pick-required, cla-not-required
