Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-08, with the labels that each got.

#499 Add Marker support to Avi Objects
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/crd_translator.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
  pkg/utils/types.go
Labels: cla-not-required

#523 NSX-T VLAN Transport zone support
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
Labels: cla-not-required

#524 update version to 1.6.1 in master branch
  Dockerfile.ako-operator
  buildsettings.json
  version.yaml
Labels: cla-not-required

#527 Fixed variable name for T1 LR
  helm/ako/templates/statefulset.yaml
Labels: cla-not-required

#528 Fixed variable name for T1 LR
  helm/ako/templates/statefulset.yaml
Labels: cherry-pick, cla-not-required

#525 VIP per namespace for EVH in VCF
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/hostname_cache.go
  internal/nodes/validator.go
  internal/status/svc_annotation.go
Labels: cla-not-required

#531 AV-120518: EVH: Enable markers/labels to avi objects by default in EVH mode
  internal/lib/lib.go
Labels: cherry-pick

#532 Add pagination support for bulk fetching vrfcontext/usable networks/SEGs
  internal/cache/controller_obj_cache.go
Labels: cla-not-required, cherry-pick-required

#533 cherry-picks to 1.5.1
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required, cherry-pick

#537 remove encoding for passthrough VS name
  internal/lib/lib.go
Labels: cla-not-required

#536 Fix: EVH Passthrough VS Update Scenario and Add Cloud Name while fetching SEG
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_evh_nodes.go
Labels: cla-not-required, cherry-pick-required

#538 remove encoding for passthrough VS name
  internal/lib/lib.go
Labels: cla-not-required, cherry-pick

#539 Fix: EVH Passthrough VS Update Scenario and Add Cloud Name while fetching SEG
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_evh_nodes.go
Labels: cherry-pick

#541 Allow AKO to identify pools for HTTPRule placement when InfraSetting is used.
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/crd_translator.go
  tests/ingresstests/ingressclass_test.go
Labels: cla-not-required, cherry-pick-required

#544 AV-121037: Enable Markers for SNI and EVH deployments for controller version >= 20.1.5
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
  internal/cache/avi_ctrl_clients.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required, cherry-pick

#542 Calculate checksum based on VS type
  internal/nodes/avi_model_nodes.go
Labels: cla-not-required, cherry-pick-required

#543 AV-121118: Add markers to Passthrough Pool and poolgroup
  internal/lib/lib.go
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required, cherry-pick-required

#545 Calculate checksum based on VS type
  internal/nodes/avi_model_nodes.go
Labels: cla-not-required, cherry-pick

#546 AV-121118: Add markers to Passthrough Pool and poolgroup
  internal/lib/lib.go
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required, cherry-pick

#548 infinite retry for all failures in rest layer
  internal/nodes/avi_model_nodes.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#551 EVH: Fix route transition secure to insecure issue
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/status/route_status.go
Labels: cla-not-required

#552 EVH: Fix route transition secure to insecure issue
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/status/route_status.go
Labels: cla-not-required, cherry-pick

#549 infinite retry for all failures in rest layer
  internal/nodes/avi_model_nodes.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick

#554 Fix EVH: Add sslkeyref to parent EVH VS
  internal/nodes/avi_model_evh_nodes.go
  internal/rest/avi_evh_obj.go
Labels: cla-not-required

#560 status update gateway and ingress when svcapi is used.
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
Labels: cla-not-required, cherry-pick-required

#553 Fix EVH: issue in setting up sslprofileref in EVH
  internal/nodes/avi_model_evh_nodes.go
  internal/rest/avi_evh_obj.go
Labels: cla-not-required

#555 doc update for passthrough Ingress
  docs/faq.md
  docs/ingress/ingress.md
  docs/values.md
Labels: documentation, cla-not-required, cherry-pick-required

#561 changed loglevel from info to warn when default secret is not present
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required, cherry-pick

#559 changed loglevel from info to warn when default secret is not present
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required, cherry-pick-required

#564 Populate valid Namespace list during AKO boot up
  internal/k8s/ako_init.go
Labels: cla-not-required, cherry-pick-required

#562 Troubleshooting for NPL with Antrea version < 1.2.0
  docs/faq.md
  docs/ingress/ingress.md
  docs/troubleshooting.md
  docs/values.md
Labels: cla-not-required

#567 release-1.5.1 docs, avi-helm-chart pending changes, new feature documentation (shchauhan)
  CHANGELOG.md
  buildsettings.json
  docs/README.md
  docs/ako_operator.md
  docs/ako_tenancy.md
  docs/akoconfig.md
  docs/crds/avinfrasetting.md
  docs/gateway-api/gateway-api.md
  docs/ingress/ingress.md
  docs/install/helm.md
  docs/install/operator.md
  docs/public_clouds.md
  docs/upgrade/upgrade.md
  docs/values.md
Labels: cla-not-required, cherry-pick-required

#566 Multi-port service support
  docs/objects.md
Labels: cla-not-required

#565 Doc updates for NSX-T cloud support in AKO
  docs/README.md
  docs/install/helm.md
  docs/values.md
Labels: cla-not-required

#568 Populate valid Namespace list during AKO boot up
  internal/k8s/ako_init.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
Labels: cla-not-required, cherry-pick

#573 AKO docs broken link fixes
  docs/crds/avinfrasetting.md
  docs/install/helm.md
  docs/install/operator.md
  docs/upgrade/upgrade.md
Labels: cla-not-required, cherry-pick-required

#575 cherry-pick: status update gateway and ingress when svcapi is used.
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
Labels: cla-not-required, cherry-pick

#577 Troubleshooting for NPL with Antrea version < 1.2.0
  docs/troubleshooting.md
Labels: cla-not-required, cherry-pick

#579 Release 1.5.1- Compatibility Guide
  CHANGELOG.md
  docs/README.md
Labels: cla-not-required, cherry-pick-required

#576 1.5.1: Doc for Openshift EVH
  docs/ako_evh.md
Labels: cla-not-required

#574 Release 1.5.1: CC to AKO migration
  docs/README.md
  docs/cc_to_ako.md
  docs/images/ako-namespace-selector.png
  docs/images/cloud-connector-gui-screenshot.png
  docs/images/cloud-connector-shell-screenshot.png
  docs/images/k8-namespace-labels.png
  docs/images/workflow-cc-to-ako.png
Labels: cla-not-required

#581 Check if value of object in cache is nil before further processing
  internal/cache/cache_utils.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required, cherry-pick-required

#582 Remove encoding from passthrough PG name
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required

#583 Remove encoding from passthrough PG name
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required, cherry-pick

#580 documentation cherry-picks from 1.5.1 to master (cherry-pick)
  CHANGELOG.md
  buildsettings.json
  docs/README.md
  docs/ako_operator.md
  docs/ako_tenancy.md
  docs/akoconfig.md
  docs/crds/avinfrasetting.md
  docs/gateway-api/gateway-api.md
  docs/ingress/ingress.md
  docs/install/helm.md
  docs/install/operator.md
  docs/public_clouds.md
  docs/upgrade/upgrade.md
  docs/values.md
Labels: cla-not-required

#585 Check if value of object in cache is nil before further processing
  internal/cache/cache_utils.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required, cherry-pick

#584 Scale Test changes for EVH support
  tests/scaletest/configs/st_testbed.json
  tests/scaletest/lib/parser.go
  tests/scaletest/scale_test.go
Labels: cla-not-required

#586 Add fqdn in vsvip for gateway and backend services.
  internal/nodes/avi_model_advl4_translator.go
Labels: cla-not-required, cherry-pick-required

#578 Public IP support and SAML Auth docs
  docs/crds/avinfrasetting.md
  docs/values.md
Labels: cla-not-required

#572 Docs: Marker support to Avi objects
  docs/objects.md
Labels: cla-not-required

#587 Initialize Avi clientPool with number of goroutines
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required, cherry-pick-required

#591 Troubleshooting for EVH
  docs/faq.md
  docs/images/Markers-on-UI.png
  docs/troubleshooting.md
Labels: cla-not-required

#592 Refresh cache even if retry count is exhausted
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick-required

#588 Gateway FQDN fix and ClientPool cherry-picks from release-1.5.1 to master
  internal/nodes/avi_model_advl4_translator.go
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required, cherry-pick

#594 Refresh cache even if retry count is exhausted
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick

#599 If default ingress controller is set fetch all Ingresses for status sync
  internal/lib/cni.go
  internal/status/ing_status.go
  tests/oshiftroutetests/oshift_secure_route_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required, cherry-pick-required

#600 remove unused .Values.imagePullSecrets from statefulset
  helm/ako/templates/statefulset.yaml
Labels: cla-not-required

#590 Fixing exit status for Scale Test
  tests/scaletest/scale_test.go
Labels: cla-not-required

#603 update build version and Avi maxVersion
  buildsettings.json
  version.yaml
Labels: cla-not-required
