Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2021-10, with the labels that each got.

#642 Add indexers for services API before setting up event handlers
  internal/k8s/ako_init.go
  internal/k8s/services_api.go
Labels: cla-not-required, cherry-pick-required

#641 change version of ingressclass to networking/v1beta1 in indexer
  internal/k8s/ako_init.go
  internal/k8s/controller.go
Labels: cla-not-required, cherry-pick-required

#640 Correct problem with status checks on CRD
  helm/ako/values.yaml
  internal/k8s/crdcontroller.go
  pkg/utils/utils.go
Labels: cla-not-required, cherry-pick

#632 Introducing locks for a couple of objects.
  internal/objects/clusteripservices.go
  internal/objects/lbservices.go
  internal/objects/store_lock_less.go
Labels: cla-not-required

#643 Revert to using locks for all objects
  internal/objects/avigraph.go
  internal/objects/clusteripservices.go
  internal/objects/lbservices.go
  internal/objects/store.go
  internal/objects/store_lock.go
Labels: cla-not-required

#628 Make the bootup cache population parallel
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/objects/avigraph.go
  internal/objects/clusteripservices.go
  internal/objects/lbservices.go
  internal/objects/resourceversions.go
  internal/objects/store_lock.go
  internal/objects/store_lock_less.go
Labels: cla-not-required, cherry-pick

#648 Add indexers for services API before setting up event handlers
  internal/k8s/ako_init.go
  internal/k8s/services_api.go
Labels: cla-not-required, cherry-pick

#650 Revert to using locks for all objects
  internal/objects/avigraph.go
  internal/objects/clusteripservices.go
  internal/objects/lbservices.go
  internal/objects/resourceversions.go
  internal/objects/store.go
  internal/objects/store_lock.go
Labels: cla-not-required, cherry-pick

#646 Multivip status update
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
  tests/advl4tests/advl4_hostname_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_route_rest_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#660 AKO Operator - CRD version upgrade, akoconfig and values.yaml changes
  ako-operator/Makefile
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/values.yaml
Labels: cla-not-required
