Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-03, with the labels that each got.

#769 [MCI] Rest and status layer changes
  Makefile
  helm/ako/crds/ako.vmware.com_clustersets.yaml
  helm/ako/crds/ako.vmware.com_multiclusteringresses.yaml
  helm/ako/templates/clusterrole.yaml
  internal/k8s/crdcontroller.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/validator.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/status/crd_status.go
  internal/status/multicluster_ing_status.go
  internal/status/status_toiler.go
  pkg/apis/ako/v1alpha1/mci.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multiclusteringresstests/multicluster_ingress_graph_test.go
  tests/multiclusteringresstests/multicluster_ingress_rest_test.go
Labels: cla-not-required

#790 Donot program fqdn for L4 via external dns when autoFQDN is disabled
  internal/nodes/avi_model_l4_translator.go
Labels: cla-not-required, cherry-pick-required

#792 Release 1.6.2 changelog additions
  CHANGELOG.md
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
Labels: cla-not-required

#793 release-1.6.2 to master pending cherry picks
  CHANGELOG.md
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/nodes/avi_model_l4_translator.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required, cherry-pick

#794 Remove stale references from go.sum and go module files
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla-not-required

#796 Skip label configuration during AviInfraSetting validation if disableStaticRouteSync set to true
  internal/k8s/crdcontroller.go
Labels: cla-not-required, cherry-pick-required

#797 Ako Operator 1.6.2 stable version changes -
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/clusterrole.yaml
  ako-operator/bundle/manifests/role.yaml
  ako-operator/bundle/metadata/annotations.yaml
  ako-operator/config/rbac/role.yaml
  ako-operator/controllers/akoconfig_controller.go
Labels: cla-not-required

#799 Setting up patch branch release-1.6.3
  buildsettings.json
  docs/README.md
  docs/install/helm.md
  docs/upgrade/upgrade.md
  version.yaml
Labels: cla-not-required

#800 [chery-pick]: Skip label configuration during AviInfraSetting validation if disableStaticRouteSync set to true
  internal/k8s/crdcontroller.go
Labels: cla-not-required

#798 Fix Service LB handling with Gateways
  internal/lib/constants.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required, cherry-pick-required

#801 [cherry-pick]: Fix Service LB handling with Gateways
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required, cherry-pick

#777 Running multiple AKO instances in cluster
  cmd/ako-main/main.go
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/clusterrolebinding.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/ingressclass.yaml
  helm/ako/templates/psppolicy.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/control_config.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/dequeue_ingestion.go
  tests/advl4tests/advl4_hostname_test.go
  tests/bootuptests/stale_obj_delete_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/l7_graph_test.go
  tests/integrationtest/l4_service_test.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
  tests/multiclusteringresstests/multicluster_ingress_graph_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#791 [MCI] AviInfraSetting with default values
  internal/nodes/route_ingress_model.go
Labels: cla-not-required

#779 FQDN aliases bug fix and optimizations
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
Labels: cla-not-required

#795 Cherry-pick from 1.7.1, 1.6.2, 1.6.1 to branch 1.5.3.
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/validator.go
  internal/rest/avi_pool_group.go
  internal/status/svc_annotation.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/utils.go
  tests/ingresstests/l7_nodeport_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required

#804 Cherry-pick commits from release-1.6.2-operator
  ako-operator/README.md
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/bundle/manifests/clusterrole.yaml
  ako-operator/bundle/manifests/role.yaml
  ako-operator/bundle/metadata/annotations.yaml
  ako-operator/config/rbac/role.yaml
  ako-operator/controllers/akoconfig_controller.go
Labels: cla-not-required, cherry-pick

#808 Doc and build setting changes to support 1.5.3
  CHANGELOG.md
  buildsettings.json
  docs/README.md
  docs/install/helm.md
  version.yaml
Labels: cla-not-required

#807 Skip label configuration during AviInfraSetting validation if disableStaticRouteSync set to true
  internal/k8s/crdcontroller.go
Labels: cla-not-required

#809 Fix Ingress delete issue with finalizer
  ako-operator/helm/ako-operator/crds/ako.vmware.com_clustersets.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_multiclusteringresses.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_serviceimports.yaml
  internal/k8s/controller.go
  internal/nodes/route_ingress_model.go
  internal/objects/ingress_to_service.go
Labels: cla-not-required

#806 Cherry-pick of FQDN aliases bug fix to 1.6.3
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
Labels: cla-not-required, cherry-pick

#805 AV-139822 - HostRule CRD changes to support Multiple FQDNs in AMKO
  ako-operator/controllers/crd.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
  docs/crds/hostrule.md
  helm/ako/crds/ako.vmware.com_hostrules.yaml
  pkg/apis/ako/v1alpha1/hostrule.go
Labels: cla-not-required

#814 Setting up branch for release-1.6.4
  buildsettings.json
  docs/README.md
  docs/install/helm.md
  docs/upgrade/upgrade.md
  version.yaml
Labels: cla-not-required

#816 AV-140383 Fixing LoadBalancer Service creation with named ports
  internal/lib/utils.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
Labels: cherry-pick
