Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-07, with the labels that each got.

#879 removing unnecessary RFC1035 check for subdomain
  internal/nodes/avi_model_l4_translator.go
Labels: cla-not-required, cherry-pick-required

#876 AV-145202 Fix floating ip warning (cherry-pick)
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required, cherry-pick

#880 Add infrasetting support with sharedvip using Service of type LB (#865)
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#881 L4 Shared VIP Infrasetting: Error out if all L4 VS does not have same avi-infra annotation
  buildsettings.json
  internal/nodes/dequeue_ingestion.go
  version.yaml
Labels: cla-not-required

#883 Doc for 1.7.2-beta
  CHANGELOG.md
  docs/objects.md
  docs/shared_vip.md
Labels: cla-not-required

#882 Regression fix: Change L4 checksum as naming convention for L4 pool is changed in 1.7.1
  internal/lib/lib.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_nodes.go
Labels: cla-not-required

#885 Release notes for 1.5.5
  CHANGELOG.md
Labels: documentation, cla-not-required

#888 Fix HttpRule: Remove mandatory check for DestCA and PkiProfile
  ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
  helm/ako/crds/ako.vmware.com_httprules.yaml
  internal/k8s/crdcontroller.go
  internal/lib/constants.go
Labels: cla-not-required

#886 Fix for the issue `Predefined health monitors are not assigned to a pool`
  internal/k8s/crdcontroller.go
  pkg/apis/ako/v1alpha1/aviinfrasetting.go
  pkg/apis/ako/v1alpha1/httprule.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
Labels: cla-not-required, cherry-pick

#887 AV-149966 set vrf to global in nodeport
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
Labels: cla-not-required, cherry-pick-required

#884 AV-149930 Fix named ports with Ingress
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/validator.go
  tests/advl4tests/advl4_hostname_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/l4_nodeport_service_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/npltests/npl_pod_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required
