Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-05, with the labels that each got.

#829 Fix for `AKO VS creation fails when using HostRule with customPorts, aliases`
  internal/cache/controller_obj_cache.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  pkg/utils/constants.go
Labels: cla-not-required, do-not-merge

#834 [Fix] Ingress class processing in fullsync
  internal/k8s/ako_init.go
Labels: cla-not-required

#835 Evh active network release 1.5.4
  CHANGELOG.md
  buildsettings.json
  docs/install/helm.md
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required, cherry-pick

#839 AV-139061 Added cloud_uuid to network api call
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/lib/lib.go
Labels: cla-not-required, cherry-pick-required

#841 [fix] AKO not honoring httprule updates in Openshift
  internal/nodes/ingress_model_rel.go
Labels: cla-not-required, cherry-pick-required

#838 AV-140317 Added ExternalUUID field in Pool servers
  internal/rest/avi_obj_pool.go
Labels: cla-not-required, cherry-pick-required

#849 Remove vipPerNamespace from user configurable parameters
  docs/akoconfig.md
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/lib/lib.go
Labels: cla-not-required

#850 Update version in master to 1.8.1
  Dockerfile.ako-operator
  buildsettings.json
  docs/install/helm.md
  docs/install/operator.md
  version.yaml
Labels: cla-not-required

#828 Add support for Shared VIP with Service of type LoadBalancer
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/objects/lbservices.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vsvip.go
  internal/status/route_status.go
  tests/integrationtest/l4_service_test.go
Labels: cla-not-required, cherry-pick-required

#845 AV-139061 Added cloud_uuid to network api call
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/lib/lib.go
Labels: cla-not-required, cherry-pick

#847 [fix] AKO not retrieving routes for an empty path
  internal/nodes/ingress_model_rel.go
Labels: cla-not-required, cherry-pick

#853 Fix status update
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required

#855 Chaning max avi version supported
  buildsettings.json
Labels: cla-not-required

#854 Docs for ServiceLB shared-VIP and hostrule alternateCertificate
  docs/crds/hostrule.md
  docs/gateway-api/gateway-api.md
  docs/shared_vip.md
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#857 Doc: Multiple AKO support
  docs/multiple-ako.md
Labels: cla-not-required
