Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-09, with the labels that each got.

#906 Support for kubernetes 1.24
  MAINTAINERS.md
  buildsettings.json
Labels: cla-not-required

#904 AviInfrasetting Support to Passthrough Routes
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#891 Sets the client-go logger as AviLogger
  ako-infra/ingestion/vcf_k8s_controller.go
  cmd/ako-main/main.go
  go.mod
  internal/cache/avi_ctrl_clients.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/crdcontroller.go
  internal/rest/avi_obj_vsvip.go
  internal/status/ing_status.go
  pkg/utils/log.go
  vendor/modules.txt
Labels: cla-not-required

#905 AV-148367: NPL optimisations
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/lib.go
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#907 AV-147609: HTTP Ingress with a single path gives a 470 error
  internal/nodes/avi_model_l7_hostname_shard.go
Labels: cla-not-required

#909 AV-153526: Avoid going through the system-namespaces on openshift and k8
  cmd/ako-main/main.go
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/k8s/advl4_controller.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/services_api.go
  internal/lib/constants.go
  internal/lib/control_config.go
  internal/lib/lib.go
  pkg/utils/utils.go
Labels: cla-not-required

#917 Fix AV-154306: Add missing code in configmap yaml
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
Labels: cla-not-required

#908 IngressClass optimisations
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  tests/ingresstests/ingressclass_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/multicloudtests/multi_cloud_test.go
Labels: cla-not-required

#918 Update NOTICE.txt
  NOTICE.txt
Labels: cla-not-required

#919 Revert "Update NOTICE.txt"
  NOTICE.txt
Labels: cla-not-required

#895 Chery-Pick: L4 Shared VIP Infrasetting: Error out if all L4 VS does not have same avi-infra annotation (#881)
  buildsettings.json
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required, cherry-pick

#913 [Cherry-pick] Doc from 1.7.1 to master: Multiple AKO support (#857)
  docs/multiple-ako.md
Labels: cla-not-required

#912 openstack support, alternate default certificate
  docs/ingress/ingress.md
  docs/openshift/openshift.md
  docs/public_clouds.md
Labels: cla-not-required

#920 AV-152331 Update README.md
  README.md
Labels: cla-not-required

#915 [Cherry-pick]Docs for ServiceLB shared-VIP and hostrule alternateCertificate (#854)
  docs/crds/hostrule.md
  docs/gateway-api/gateway-api.md
  docs/shared_vip.md
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#914 [Cherry-pick] Release-1.7.1: Helm updates, compatability matrix update, update to values.yaml, changelog addition
  CHANGELOG.md
  docs/README.md
  docs/install/helm.md
  docs/values.md
Labels: cla-not-required

#921 [AV-154444] corrects the 'invalid type for address' warning logs coming in AKO log
  internal/rest/avi_obj_vsvip.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#923 VKAL-15587 Update Avi-init-secret
  internal/lib/constants.go
  internal/lib/dynamic_client.go
  internal/lib/lib.go
Labels: cla-not-required

#922 [AV-154711] fix for AKO restart issue
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required

#910 Set min and max controller versions for 1.8.1
  buildsettings.json
Labels: cla-not-required

#916 Istio mTLS support
  cmd/ako-main/main.go
  go.mod
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/avi_obj_pool.go
  internal/rest/dequeue_nodes.go
  vendor/modules.txt
Labels: cla-not-required

#928 Doc: adding blockedNamespaceList documentation
  docs/install/helm.md
  docs/values.md
Labels: cla-not-required

#927 Doc: Aviinfrasetting support in Passthrough VS
  docs/crds/avinfrasetting.md
  docs/ingress/ingress.md
  docs/openshift/objects.md
  docs/shared_vip.md
Labels: cla-not-required

#926 Fix for UT failures
  Makefile
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/multicloudtests/multi_cloud_test.go
Labels: cla-not-required

#930 Fix for statefulset yaml issue
  helm/ako/templates/statefulset.yaml
Labels: cla-not-required, cherry-pick-required

#931 Fixes the issue with values.yaml
  helm/ako/values.yaml
Labels: cla-not-required, cherry-pick-required

#929 Fix for UT failures
  Makefile
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/multicloudtests/multi_cloud_test.go
Labels: cla-not-required, cherry-pick

#924 [AV-154259] fix to clear cache during partial delete
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick-required

#933 [cherry-pick to release 1.8.1]fix to clear cache during partial delete
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick

#934 fix for AV-156686
  internal/k8s/ako_init.go
Labels: cla-not-required, cherry-pick-required

#932 Fix for helm chart issues
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
Labels: cla-not-required, cherry-pick

#935 fix for AV-156686
  internal/k8s/ako_init.go
Labels: cla-not-required, cherry-pick

#944 Fixes few issues with log and issue with caching Nodes in NodePort mode
  cmd/ako-main/main.go
  cmd/infra-main/main.go
  internal/objects/nodes.go
  internal/rest/ssl_key_certificate.go
  pkg/utils/log.go
Labels: cla-not-required

#947 AV-156959 Nodenetwork list mandatory fix for nsx-t vlan
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/rest/avi_obj_pool.go
Labels: cla-not-required

#948 AV-156960 Add vip placement from vip network for nsxt vlan
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required
