Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-08, with the labels that each got.

#892 Doc changes for AKO 1.7.2
  CHANGELOG.md
  Dockerfile.ako-operator
  docs/README.md
  docs/install/helm.md
Labels: cla-not-required

#896 Documentation update for 1.7.2 release
  CHANGELOG.md
Labels: cla-not-required

#889 AV-149930 Fix named ports with Ingress (cherry-pick)
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/validator.go
  tests/advl4tests/advl4_hostname_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/l4_nodeport_service_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/npltests/npl_pod_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required, cherry-pick

#899 Changelogs correction
  CHANGELOG.md
Labels: documentation, cla-not-required

#890 AV-149966 set vrf to global in nodeport (cherry-pick)
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
Labels: cla-not-required, cherry-pick

#897 Update README.md
  README.md
Labels: cla-not-required, do-not-review

#901 AV-150130 Revert "Revert "Update README.md""
  README.md
Labels: cla-not-required

#893 [Cherry-pick]: Fix HttpRule: Remove mandatory check for DestCA and PkiProfile (#888)
  ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
  helm/ako/crds/ako.vmware.com_httprules.yaml
  internal/k8s/crdcontroller.go
  internal/lib/constants.go
Labels: cla-not-required

#894 [Cherry-pick]: Regression fix: [AV-149730] Change L4 checksum as naming convention for L4 pool is changed in 1.7.1
  internal/lib/lib.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_nodes.go
Labels: cla-not-required, cherry-pick

#902 AV-150130
  README.md
Labels: cla-not-required

#903 Revert "AV-150130"
  README.md
Labels: cla-not-required
