Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-02, with the labels that each got.

#746 Doc update for AKO statefulset annotation change cherry-pick to master
  docs/faq.md
Labels: cla-not-required, cherry-pick

#762 Cherry-pick: AKO Operator 1.6.1 bundle changes
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/bundle/manifests/clusterrole.yaml
  ako-operator/bundle/manifests/clusterrolebinding.yaml
  ako-operator/bundle/manifests/rb.yaml
  ako-operator/bundle/manifests/role.yaml
  ako-operator/bundle/manifests/rolebinding.yaml
  ako-operator/bundle/manifests/serviceaccount.yaml
  ako-operator/bundle/metadata/annotations.yaml
Labels: cla-not-required, cherry-pick, do-not-merge

#763 doc update for 1.6.2 release
  CHANGELOG.md
  buildsettings.json
  docs/README.md
  docs/install/helm.md
  docs/upgrade/upgrade.md
  version.yaml
Labels: cla-not-required

#761 AV-136288: Ingresses are not getting synced to AVI After changing deleteconfig value from True to False
  internal/k8s/ako_init.go
  internal/lib/lib.go
Labels: cla-not-required

#758 VCF: Deconfiguring infra configurations on namespace delete
  ako-infra/avirest/handle_deconfig.go
  ako-infra/ingestion/avi_infra_controller.go
  ako-infra/ingestion/vcf_k8s_controller.go
  cmd/infra-main/main.go
  internal/lib/advl4.go
  internal/lib/avi_api.go
  internal/lib/constants.go
  internal/lib/dynamic_client.go
  internal/lib/finalizer_utils.go
  internal/lib/servicesapi.go
  internal/status/ing_status.go
Labels: cla-not-required

#754 [MCI] Ingestion layer changes
  cmd/ako-main/main.go
  go.mod
  go.sum
  helm/ako/crds/ako.vmware.com_multiclusteringresses.yaml
  helm/ako/crds/ako.vmware.com_serviceimports.yaml
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/status/crd_status.go
  pkg/apis/ako/v1alpha1/mci.go
  pkg/apis/ako/v1alpha1/register.go
  pkg/apis/ako/v1alpha1/zz_generated.deepcopy.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/ako_client.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/clusterset.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/fake/fake_ako_client.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/fake/fake_clusterset.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/fake/fake_multiclusteringress.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/fake/fake_serviceimport.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/generated_expansion.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/multiclusteringress.go
  pkg/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/serviceimport.go
  pkg/client/v1alpha1/informers/externalversions/ako/v1alpha1/clusterset.go
  pkg/client/v1alpha1/informers/externalversions/ako/v1alpha1/interface.go
  pkg/client/v1alpha1/informers/externalversions/ako/v1alpha1/multiclusteringress.go
  pkg/client/v1alpha1/informers/externalversions/ako/v1alpha1/serviceimport.go
  pkg/client/v1alpha1/informers/externalversions/generic.go
  pkg/client/v1alpha1/listers/ako/v1alpha1/clusterset.go
  pkg/client/v1alpha1/listers/ako/v1alpha1/expansion_generated.go
  pkg/client/v1alpha1/listers/ako/v1alpha1/multiclusteringress.go
  pkg/client/v1alpha1/listers/ako/v1alpha1/serviceimport.go
  pkg/utils/constants.go
  pkg/utils/types.go
  pkg/utils/utils.go
  vendor/modules.txt
Labels: cla-not-required

#770 Validate enableSSL on listener Port only when listener settings are configured
  CHANGELOG.md
  internal/k8s/crdcontroller.go
Labels: cla-not-required, cherry-pick-required

#771 Fix to configure appProfile, httpPolicies, datascripts for EVH/SNI parent VSes
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#772 [cherry-pick]: Status update push to queue fixes, ingress/svc/route update check enhancements
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
Labels: cla-not-required, cherry-pick

#773 Sets the non significant log duration as infinite by default
  internal/nodes/crd_translator.go
Labels: cla-not-required, cherry-pick-required

#774 Fix to configure appProfile, httpPolicies, datascripts for EVH/SNI parent VSes
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_vs.go
Labels: cla-not-required, cherry-pick

#767 AKO Operator 1.6.2 updated documentation
  ako-operator/README.md
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/crd.go
  ako-operator/helm/ako-operator/values.yaml
  docs/akoconfig.md
  docs/install/operator.md
Labels: cla-not-required

#764 Openstack support for AKO
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required

#775 Update deconfiguration logic by watching over Workload namespace
  ako-infra/ingestion/constants.go
  ako-infra/ingestion/vcf_k8s_controller.go
  cmd/ako-main/main.go
  cmd/infra-main/main.go
  internal/lib/dynamic_client.go
  internal/lib/lib.go
Labels: cla-not-required

#778 Add tenant and api version for fetching authtoken
  internal/cache/avi_ctrl_clients.go
  internal/lib/avi_api.go
  internal/lib/lib.go
Labels: cla-not-required

#781 Cherry-picking commits from release-1.6.2-operator
  ako-operator/README.md
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/metadata/annotations.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/crd.go
  ako-operator/helm/ako-operator/values.yaml
  docs/akoconfig.md
  docs/install/operator.md
Labels: cla-not-required, cherry-pick

#785 Fix hostrule datascript attachment in Parent VSes SNI/Passthrough
  internal/rest/avi_obj_vs.go
Labels: cla-not-required, cherry-pick-required

#784 Remove overwriting controllerVersion on POST/PUT/DELETE api calls
  ako-infra/avirest/handle_netinfo.go
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/rest_operation.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required, cherry-pick

#788 Remove overwriting controllerVersion on POST/PUT/DELETE api calls
  ako-infra/avirest/handle_netinfo.go
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/rest_operation.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required, cherry-pick-required

#789 AV-137368: Add tenant and api version for fetching authtoken
  internal/cache/avi_ctrl_clients.go
  internal/lib/avi_api.go
  internal/lib/lib.go
Labels: cla-not-required, cherry-pick-required
