Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-11, with the labels that each got.

#961 AV-159660: Fixes an issue in populating VS DataScript cache when AKO encounters 409 error
  internal/cache/controller_obj_cache.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick-required

#971 Fixed subnet update in network
  ako-infra/avirest/handle_netinfo.go
Labels: cla-not-required

#972 Cherry-pick of issue fix in populating VS DataScript cache
  internal/cache/controller_obj_cache.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick

#950 Cherry-pick of fixes added for log issues and issue with caching Nodes in NodePort mode
  cmd/ako-main/main.go
  cmd/infra-main/main.go
  internal/objects/nodes.go
  internal/rest/ssl_key_certificate.go
  pkg/utils/log.go
Labels: cla-not-required, cherry-pick

#949 Adds a known issue to release-1.7.1 changelogs
  CHANGELOG.md
Labels: documentation, cla-not-required

#957 AV-157950 : AKO Operator 1.8.1 Release and RH Certification
  ako-operator/README.md
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/crd.go
  ako-operator/controllers/statefulset.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/akoconfig.md
  docs/install/operator.md
Labels: cla-not-required

#945 AV-156959 Nodenetwork list mandatory fix for nsx-t vlan
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/rest/avi_obj_pool.go
Labels: cla-not-required

#974 Changing version to 1.8.2. Also adding controller version 22.1.2 support
  buildsettings.json
  docs/README.md
  docs/install/helm.md
  docs/upgrade/upgrade.md
  version.yaml
Labels: cla-not-required

#962 [HA] Ingestion Layer code changes
  cmd/ako-main/main.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/leader_election_callbacks.go
  internal/k8s/validator.go
  internal/lib/control_config.go
  pkg/utils/constants.go
  pkg/utils/leader_election.go
  tests/advl4tests/advl4_hostname_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/l7_graph_test.go
  tests/integrationtest/l4_nodeport_service_test.go
  tests/integrationtest/l4_service_test.go
  tests/multiclusteringresstests/multicluster_ingress_graph_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#977 AV-158136: Validate enableSSL on listener Port only when listener settings are configured
  internal/k8s/crdcontroller.go
Labels: cla-not-required

#968 VKAL-16712: LoadBalancers and Guest Clusters are not created when 2 SE Groups exist
  cmd/ako-main/main.go
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required

#975 AV-159292: Fix for Error datascript for passthrough VS
  internal/lib/constants.go
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required

#987 AV-159292: Fix for Error datascript for passthrough VS
  internal/lib/constants.go
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required

#981 AV-157761 Status update for IPv6 AKO
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required, cherry-pick-required

#991 AV-156960 Add vip placement from vip network for nsxt vlan
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required

#992 AV-160069 Fix error logs with istio on AKO bootup
  cmd/ako-main/main.go
  internal/lib/lib.go
Labels: cla-not-required

#993 AV-159603 secure ingress with Istio fix
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required

#990 AV-157761 Status update for IPv6 AKO
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required

#982 [HA] Changes in Statefulset
  helm/ako/templates/statefulset.yaml
Labels: cla-not-required

#995 AKO 1.8.2 changelog and values.yaml modification
  CHANGELOG.md
  docs/values.md
  helm/ako/values.yaml
Labels: cla-not-required, cherry-pick-required

#978 [HA] Rest layer code changes
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/k8s_utils.go
  internal/rest/rest_operation.go
  internal/rest/rest_utils.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required

#986 [HA] Status layer code changes
  internal/k8s/ako_init.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/multicluster_ing_status.go
  internal/status/route_status.go
  internal/status/status_publisher.go
  internal/status/status_toiler.go
  internal/status/svc_annotation.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
Labels: cla-not-required

#996 Changing K8 min and max version supported in 1.9.1
  buildsettings.json
Labels: cla-not-required
