Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-01, with the labels that each got.

#748 Updated version to 1.7.1 in master
  Dockerfile.ako-operator
  buildsettings.json
  version.yaml
Labels: cla-not-required

#749 Allow pkiProfile reference in HTTPRule, native k8s secret in HostRule
  ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
  cmd/ako-main/main.go
  go.sum
  helm/ako/crds/ako.vmware.com_hostrules.yaml
  helm/ako/crds/ako.vmware.com_httprules.yaml
  internal/k8s/crdcontroller.go
  internal/lib/constants.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/nodes/validator.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_pool.go
  internal/status/ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
  pkg/apis/ako/v1alpha1/hostrule.go
  pkg/apis/ako/v1alpha1/httprule.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required

#750 set T1 LR in the VSVip of Passthrough VS
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required

#752 Save cloud properties in cache if dns not provided
  internal/cache/controller_obj_cache.go
  internal/rest/avi_obj_pool.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required

#753 set T1 LR in the VSVip of Passthrough VS
  internal/nodes/avi_model_tls_passthrough.go
Labels: cla-not-required, cherry-pick

#751 Hostrule fixes relating to fqdnType Wildcard and changes between fqdnTypes
  internal/nodes/dequeue_ingestion.go
  internal/nodes/hostname_cache.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/validator.go
  internal/objects/crdrules.go
  tests/evhtests/l7_evh_crd_test.go
Labels: cla-not-required

#744 Bringing back syncNamespace and advancedL4 in akoconfig CRD for 1.6.1
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
Labels: cla-not-required

#759 [cherry-picks]: hostrule and cloud cache fixes
  internal/cache/controller_obj_cache.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/hostname_cache.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/validator.go
  internal/objects/crdrules.go
  internal/rest/avi_obj_pool.go
  internal/rest/ssl_key_certificate.go
  tests/evhtests/l7_evh_crd_test.go
Labels: cla-not-required, cherry-pick

#760 Cherry-pick: Bringing back syncNamespace and advancedL4 in akoconfig CRD for 1.6.1
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
Labels: cla-not-required, cherry-pick

#757 AKO Operator 1.6.1 bundle changes
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/bundle/manifests/clusterrole.yaml
  ako-operator/bundle/manifests/clusterrolebinding.yaml
  ako-operator/bundle/manifests/rb.yaml
  ako-operator/bundle/manifests/role.yaml
  ako-operator/bundle/manifests/rolebinding.yaml
  ako-operator/bundle/manifests/serviceaccount.yaml
  ako-operator/bundle/metadata/annotations.yaml
Labels: cla-not-required

#741 Control AKO Event broadcasting using ConfigMap `enableEvents`
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/akoconfig.md
  docs/install/helm.md
  docs/install/operator.md
  docs/troubleshooting/events.md
  docs/values.md
  helm/ako/templates/configmap.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/control_config.go
  pkg/utils/events.go
Labels: cla-not-required, cherry-pick-required
