Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2022-12, with the labels that each got.

#989 AV-157950 : Bundle changes for AKO Operator 1.8.1 Release and RH Cert…
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/bundle/metadata/annotations.yaml
  ako-operator/controllers/crd.go
Labels: cla-not-required

#994 Support for LoadBalancerIP annotation
  internal/lib/constants.go
  internal/lib/utils.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#998 [HA] Configmap changes
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/leader_election_callbacks.go
  internal/status/statefulset_status.go
  internal/status/status_publisher.go
  pkg/utils/full_sync_worker.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
Labels: cla-not-required

#976 [AV-150821] fix for status IPs not getting updated properly for some Ingresses/Routes
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#1003 Cherrypicks from multiple PRs
  cmd/ako-main/main.go
  docs/crds/avinfrasetting.md
  docs/install/helm.md
  docs/istio_support.md
  docs/values.md
  internal/lib/lib.go
  internal/nodes/avi_model_l7_translator.go
  internal/rest/avi_obj_vsvip.go
Labels: cla-not-required, cherry-pick

#1010 AV-163703 : Support SCTP protocol in AKO for LoadBalancer and other L4 services
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  pkg/utils/constants.go
  pkg/utils/types.go
Labels: cla-not-required

#1012 [Bug fix] Fix for VSVIP key collection coming as empty in VS cache
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#966 Service migration script
  scripts/service_migration.py
Labels: cla-not-required

#1009 [HA] Sync HA code to master
  ako-infra/avirest/handle_netinfo.go
  cmd/ako-main/main.go
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/statefulset.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/leader_election_callbacks.go
  internal/k8s/validator.go
  internal/lib/control_config.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vrf.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/dequeue_nodes.go
  internal/rest/k8s_utils.go
  internal/rest/rest_operation.go
  internal/rest/rest_utils.go
  internal/rest/ssl_key_certificate.go
  internal/status/advl4_status.go
  internal/status/ing_status.go
  internal/status/multicluster_ing_status.go
  internal/status/route_status.go
  internal/status/statefulset_status.go
  internal/status/status_publisher.go
  internal/status/status_toiler.go
  internal/status/svc_annotation.go
  internal/status/svc_status.go
  internal/status/svcapi_status.go
  pkg/utils/constants.go
  pkg/utils/full_sync_worker.go
  pkg/utils/leader_election.go
  tests/advl4tests/advl4_hostname_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/integrationtest/l4_nodeport_service_test.go
  tests/integrationtest/l4_service_test.go
  tests/multiclusteringresstests/multicluster_ingress_graph_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#1015 AV-162992 add alternate cert to avi controller with a different name
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required

#999 AV-151198: Do not create SNI/EVH Child VS if there is an issue with ertificate. Do not block processing of other SNI childs if there is an issue in other child.
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
Labels: cla-not-required

#1014 AV-160077 Add AVI default SSL profile to pool to support older AVI versions
  internal/nodes/avi_model_nodes.go
Labels: cla-not-required

#1013 AV-160076 Cleanup istio resources after istio is disabled
  internal/cache/controller_obj_cache.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#1011 Release 1.8.2 operator
  ako-operator/README.md
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/bundle/metadata/annotations.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/crd.go
  ako-operator/controllers/statefulset.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/akoconfig.md
  docs/install/operator.md
Labels: cla-not-required

#1004 AV-162881 use avi certificateref in checksum calculation
  internal/nodes/avi_model_nodes.go
Labels: cla-not-required

#1019 [doc] AV-164899: Corrects the podSecurityContext reference
  docs/values.md
Labels: documentation, cla-not-required

#1021 fix for AV-164932
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#1024 AV-163975 : Bundle changes for AKO Operator 1.8.2 Release and RH Cert…
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
Labels: cla-not-required
