Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2023-06, with the labels that each got.

#1157 ICAP documentation
  docs/crds/hostrule.md
Labels: cla-not-required, cherry-pick

#1161 AV-180047: fix: AKO Bootup time is 36 min with 193 Nodes and 9k ingresses and 4k pods
  internal/k8s/ako_init.go
Labels: cla-not-required, cherry-pick-required

#1163 Added cert data to Avi client
  ako-infra/ingestion/vcf_k8s_controller.go
  go.mod
  go.sum
  internal/k8s/ako_init.go
  internal/lib/avi_api.go
  internal/rest/dequeue_nodes.go
  pkg/utils/avi_rest_utils.go
  vendor/modules.txt
Labels: cla-not-required

#1160 AV-180281 : Add support for Cilium CNI in Kubernetes with AKO
  Makefile
  docs/install/helm.md
  docs/values.md
  helm/ako/templates/clusterrole.yaml
  helm/ako/values.yaml
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/dynamic_client.go
  tests/calicotests/static_route_test.go
  tests/cnitests/static_route_test.go
Labels: cla-not-required

#1164 AV-179484: Fixes the issue of no status when insecure Edge Termination Policy set as Allow
  internal/status/route_status.go
Labels: cla-not-required, cherry-pick

#1158 AV-134285 : Documentation for L4Rule CRD
  docs/crds/l4rule.md
  docs/shared_vip.md
Labels: cla-not-required, cherry-pick

#1165 AV-180342: Fix: shared vip service support for mix protocols. Mix protocol support was not working when SCTP protocol is specified with either UDP/TCP
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_obj_vs.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/hatests/follower_l4_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/lib.go
  tests/integrationtest/l4_crd_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/multiclusteringresstests/multicluster_ingress_graph_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/lib.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/oshiftroutetests/oshift_route_namespace_sync_test.go
  tests/oshiftroutetests/oshift_route_passthrough_test.go
  tests/oshiftroutetests/oshift_route_rest_test.go
  tests/oshiftroutetests/oshift_secure_route_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#1166 AV-180638: Fix for the network profile for SCTP not coming as expected
  internal/nodes/crd_translator.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  tests/dedicatedevhtests/l7_dedicated_rest_test.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_rest_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/l7_rest_test.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required, cherry-pick-required

#1168 Revert Alb sdk and cert refresh changes
  go.mod
  go.sum
  internal/lib/avi_api.go
  internal/rest/dequeue_nodes.go
  third_party/github.com/vmware/alb-sdk/go/session/avisession.go
  vendor/modules.txt
Labels: cla-not-required

#1159 Changelogs and compatibility matrix for release 1.10.1
  CHANGELOG.md
  buildsettings.json
  docs/README.md
Labels: cla-not-required, cherry-pick-required

#1180 AV-180047: fix: AKO Bootup time is 36 min with 193 Nodes and 9k ingresses and 4k pods (#1161)
  internal/k8s/ako_init.go
Labels: cla-not-required, cherry-pick

#1172 AV-169294 : Documentation for Cilium CNI support with AKO (#1162)
  docs/cilium.md
Labels: cla-not-required, cherry-pick

#1171 AV-180281 : Add support for Cilium CNI in Kubernetes with AKO (#1160)
  Makefile
  docs/install/helm.md
  docs/values.md
  helm/ako/templates/clusterrole.yaml
  helm/ako/values.yaml
  internal/k8s/controller.go
  internal/lib/constants.go
  internal/lib/dynamic_client.go
  tests/calicotests/static_route_test.go
  tests/cnitests/static_route_test.go
Labels: cla-not-required, cherry-pick

#1170 AV-152365 : Documentation for SSORule CRD (#1153)
  docs/crds/ssorule.md
Labels: cla-not-required, cherry-pick

#1169 AV-165148 : Documentation for OVN-Kubernetes CNI (#1155)
  docs/ovn-kubernetes.md
Labels: cla-not-required, cherry-pick

#1167 doc for HTTP2 flow in FE + change to keep union of hostrule and aviinfra listeners
  docs/crds/avinfrasetting.md
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required, cherry-pick

#1173 AV-180638: Fix for the network profile for SCTP not coming as expected
  internal/nodes/crd_translator.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  tests/dedicatedevhtests/l7_dedicated_rest_test.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_rest_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/l7_rest_test.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required, cherry-pick

#1174 [Cherry-pick]Changelogs and compatibility matrix for release 1.10.1
  CHANGELOG.md
  buildsettings.json
  docs/README.md
Labels: cla-not-required, cherry-pick

#1156 AV-179484: Fixes the issue of no status when insecure Edge Termination Policy set as Allow
  internal/status/route_status.go
Labels: cla-not-required

#1181 AV-180342: Fix: shared vip service support for mix protocols. Mix protocol support was not working when SCTP protocol is specified with either UDP/TCP (#1165)
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_obj_vs.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/hatests/follower_l4_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/lib.go
  tests/integrationtest/l4_crd_test.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/multiclusteringresstests/multicluster_ingress_graph_test.go
  tests/namespacesynctests/l7_ingress_namespace_sync_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/lib.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/oshiftroutetests/oshift_route_namespace_sync_test.go
  tests/oshiftroutetests/oshift_route_passthrough_test.go
  tests/oshiftroutetests/oshift_route_rest_test.go
  tests/oshiftroutetests/oshift_secure_route_test.go
  tests/temp/temp_sni_to_pool_test.go
Labels: cla-not-required

#1183 Updates the Ubuntu version to 20.04 in go.yml
  .github/workflows/go.yml
Labels: cla-not-required

#1184 Cherry-picks UT fixes to release-1.7.4
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1175 AV-179162: No Autogenerated domain for Dedicated Shard VS when AutoFQDN is `flat` or `default`
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
Labels: cla-not-required, cherry-pick-required

#1179 AV-168279: Add retry logic for kube-api access.
  internal/lib/control_config.go
Labels: cla-not-required, cherry-pick

#1186 AKO 1.8.2 support for 22.1.4
  docs/README.md
Labels: cla-not-required

#1185 Doc changes for release-1.7.4
  buildsettings.json
  docs/README.md
  docs/install/helm.md
  version.yaml
Labels: cla-not-required

#1188 Changelogs for 1.7.4 release
  CHANGELOG.md
Labels: cla-not-required, cherry-pick-required
