Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2023-07, with the labels that each got.

#1195 AV-183324: Helm changes for Gateway APIs
  Dockerfile.ako-gateway-api
  Makefile
  ako-gateway-api/cache/cache_utils.go
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/objects/nodes.go
  ako-gateway-api/rest/dequeue_nodes.go
  ako-gateway-api/retry/dequeue_retry.go
  ako-gateway-api/status/gateway_status.go
  cmd/gateway-api/main.go
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/gatewayclass.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  tests/helmtests/clusterrole_test.yaml
  tests/helmtests/gatewayclass_test.yaml
  tests/helmtests/statefulset_test.yaml
Labels: cla-not-required

#1192 AV-183113: Updated k8s version to 1.27 in buildsettings
  buildsettings.json
  version.yaml
Labels: cla-not-required

#1187 AV-179162: No Autogenerated domain for Dedicated Shard VS when AutoFQDN is flat or default
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
Labels: cla-not-required, cherry-pick

#1191 AV-179207- Do not add gslbFqdn to vsvip fqdn in Dedicated mode
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required, cherry-pick

#1196 AV-180534: Handle Concurrent update to VRFContext
  internal/rest/avi_obj_vrf.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
Labels: cla-not-required

#1201 Code cleanup and a few bug fixes
  Makefile
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/lib/constants.go
  ako-gateway-api/lib/control_config.go
  cmd/gateway-api/main.go
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  vendor/modules.txt
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/interface.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/gateway.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/gatewayclass.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/grpcroute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/httproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/interface.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/referencegrant.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/tcproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/tlsroute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/apis/v1alpha2/udproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/factory.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/generic.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/expansion_generated.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/gateway.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/gatewayclass.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/grpcroute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/httproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/referencegrant.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/tcproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/tlsroute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/listers/apis/v1alpha2/udproute.go
Labels: cla-not-required

#1200 Changelogs for 1.7.4 release
  CHANGELOG.md
Labels: cla-not-required, cherry-pick

#1204 AV-183081 Ingestion layer UT for Gateway
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/objects/gateway_store.go
  ako-gateway-api/tests/gateway_test.go
  ako-gateway-api/tests/gateway_utils.go
  vendor/modules.txt
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/fake/doc.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/fake/register.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/doc.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_apis_client.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_gateway.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_gatewayclass.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_grpcroute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_httproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_referencegrant.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_tcproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_tlsroute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_udproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1beta1/fake/doc.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_apis_client.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_gateway.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_gatewayclass.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_httproute.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_referencegrant.go
Labels: cla-not-required

#1190 AV-182960 : Fix to support mixed protocols for ports in LoadBalancer services and Gateway Services API
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  internal/rest/avi_obj_vs.go
  internal/status/svcapi_status.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#1205 AV-183627 : Remove CTRL_CA_DATA env variable from AKO Statefulset definition as it violates CNTR-K8-001160 (#1199)
  helm/ako/templates/statefulset.yaml
Labels: cla-not-required, cherry-pick

#1198 AV-183158 : Code and Document changes for AKO Operator 1.10.1 Release
  Dockerfile.ako-operator
  ako-operator/README.md
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/crd.go
  ako-operator/controllers/role.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_l4rules.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_ssorules.yaml
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/akoconfig.md
  docs/install/operator.md
Labels: cla-not-required, cherry-pick-required

#1203 AV-183407: Fix: AVI shows the segment twice as it receives from 2 different CDVS.
  buildsettings.json
  go.mod
  go.sum
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/k8s/validator.go
  internal/lib/lib.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vsvip.go
  pkg/apis/ako/v1alpha1/aviinfrasetting.go
  pkg/client/v1alpha1/clientset/versioned/fake/register.go
  pkg/client/v1alpha1/clientset/versioned/scheme/register.go
  tests/avimockobjects/crd_network_ipam1.json
  tests/avimockobjects/crd_network_ipam2.json
  tests/avimockobjects/crd_network_ipam3.json
  tests/avimockobjects/crd_network_mock.json
  tests/integrationtest/lib.go
  vendor/github.com/jupp0r/go-priority-queue/LICENSE
  vendor/github.com/jupp0r/go-priority-queue/README.md
  vendor/github.com/jupp0r/go-priority-queue/priorty_queue.go
  vendor/modules.txt
  version.yaml
Labels: cla-not-required

#1211 AV-183086 Graph Layer changes for Gateway API
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/objects/gateway_store.go
  cmd/gateway-api/main.go
  helm/ako/templates/statefulset.yaml
Labels: cla-not-required

#1212 AV-183085: [GatewayAPI]Event handlers for HTTP Route object
  ako-gateway-api/k8s/gateway_controller.go
Labels: cla-not-required

#1178 Sync release 1.9.3 tkg to master
  ako-infra/avirest/handle_netinfo.go
  ako-infra/avirest/rest.go
  ako-infra/ingestion/avi_infra_controller.go
  ako-infra/ingestion/vcf_k8s_controller.go
  cmd/infra-main/main.go
  go.mod
  go.sum
  internal/cache/controller_obj_cache.go
  internal/k8s/advl4_controller.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/avi_api.go
  internal/lib/constants.go
  internal/lib/dynamic_client.go
  internal/lib/lib.go
  internal/lib/utils.go
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
  internal/nodes/avi_model_tls_passthrough.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/objects/wcp.go
  internal/rest/dequeue_nodes.go
  internal/rest/rest_operation.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/constants.go
  pkg/utils/full_sync_worker.go
  pkg/utils/utils.go
  tests/integrationtest/l4_service_test.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#1214 Fix: Fixed logic for finding overlap IPaddress. Added debug logs
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#1213 AV-183085: [GatewayAPI] HTTPRoute Ingestion layer validation and Status layer code
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/lib/constants.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/status/gateway_status.go
  ako-gateway-api/status/httproute_status.go
  ako-gateway-api/status/status.go
  ako-gateway-api/tests/ingestion/gateway_test.go
  ako-gateway-api/tests/status/gateway_test.go
  ako-gateway-api/tests/status/httproute_test.go
  ako-gateway-api/tests/utils.go
Labels: cla-not-required

#1217 Changelog for 1.10.2
  CHANGELOG.md
  docs/ako_ha.md
  docs/install/helm.md
Labels: cla-not-required, cherry-pick-required

#1207 AV-183230: Bugfix for extDNS incompatibility with shared-vip annotation
  internal/nodes/avi_model_advl4_translator.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1219 AV-183158 : Fix linting issue in clusterrole.yaml for AKO Operator 1.10.1 Release
  ako-operator/bundle/manifests/clusterrole.yaml
Labels: cla-not-required, cherry-pick-required

#1218 correct documentation for aviinfrasetting
  docs/crds/avinfrasetting.md
Labels: cla-not-required

#1224 AV-183082 Add Graph Layer UTs
  ako-gateway-api/tests/graphlayer/gateway_test.go
  ako-gateway-api/tests/graphlayer/gatewayclass_test.go
Labels: cla-not-required
