Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2023-08, with the labels that each got.

#1223 AV-183086: [GatewayAPI] Initial commit of child VS creation code
  ako-gateway-api/nodes/avi_model_l4_translator.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/nodes/route_model.go
  ako-gateway-api/objects/gateway_store.go
  internal/nodes/avi_model_evh_nodes.go
Labels: cla-not-required

#1225 AV-184601: Fix for HTTPRule with empty LBAlgorithm
  internal/nodes/crd_translator.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required

#1228 Using SEG mgmt network for finding out host overlap
  buildsettings.json
  docs/ako_ha.md
  docs/install/helm.md
  helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/crdcontroller.go
  internal/k8s/validator.go
  internal/lib/lib.go
  internal/rest/avi_obj_vsvip.go
  vendor/modules.txt
Labels: cla-not-required

#1230 AV-184601: Fix for HTTPRule with empty LBAlgorithm
  internal/nodes/crd_translator.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required, cherry-pick

#1235 Change version to 1.10.3
  version.yaml
Labels: cla-not-required

#1236 AV-186404: Fix AKO crash on reboot when IPV6 vip is there
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#1232 Updates the version to 1.7.5
  buildsettings.json
  docs/README.md
  docs/install/helm.md
  version.yaml
Labels: cla-not-required

#1234 AV-180357 : Add Hostname from external-dns annotation only when AutoFQDN is flat or default
  internal/nodes/avi_model_l4_translator.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required, cherry-pick

#1239 Fix: Use mgmt network from confimap SE group if aviinfrasetting SEG is not present
  internal/k8s/crdcontroller.go
Labels: cla-not-required

#1231 AKO 1.10.3 documents changes for Aviinfrasetting
  docs/crds/avinfrasetting.md
  docs/faq.md
  docs/install/helm.md
  docs/upgrade/upgrade.md
  docs/values.md
Labels: cla-not-required

#1237 Doc corrections
  docs/crds/l4rule.md
  docs/gateway-api/gateway-api.md
  docs/objects.md
Labels: documentation, cla-not-required, cherry-pick-required

#1243 Fix: Use mgmt network from confimap SE group if aviinfrasetting SEG is not present
  internal/k8s/crdcontroller.go
  internal/k8s/validator.go
Labels: cla-not-required

#1242 Release-1.10.3: helm based installation changes
  docs/README.md
  docs/install/helm.md
  docs/openshift/openshift_helm.md
Labels: cla-not-required, cherry-pick-required

#1244 Helm based installation changes for release-1.7.5
  docs/install/helm.md
  docs/openshift/openshift_helm.md
Labels: cla-not-required

#1240 Release-1.10.3-Changelog
  CHANGELOG.md
Labels: cla-not-required, cherry-pick-required

#1245 HTTP Policies for GatewayAPI
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/nodes/route_model.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
Labels: cla-not-required

#1250 [GatewayAPI]code to process Service, Endpoint and Route objects
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/objects/gateway_store.go
  ako-gateway-api/tests/graphlayer/gateway_test.go
  ako-gateway-api/tests/graphlayer/httproute_test.go
  ako-gateway-api/tests/status/httproute_test.go
  ako-gateway-api/tests/utils.go
Labels: cla-not-required

#1246 Changelogs for release-1.7.5
  CHANGELOG.md
Labels: cla-not-required, cherry-pick

#1221 AV-183158 : AKO Operator 1.10.1 Release and RH Certification
  Dockerfile.ako-operator
  ako-operator/README.md
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/bundle.Dockerfile
  ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
  ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
  ako-operator/bundle/manifests/clusterrole.yaml
  ako-operator/bundle/metadata/annotations.yaml
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/controllers/akoconfig_controller.go
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/crd.go
  ako-operator/controllers/role.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_l4rules.yaml
  ako-operator/helm/ako-operator/crds/ako.vmware.com_ssorules.yaml
  ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
  ako-operator/helm/ako-operator/templates/akoconfig.yaml
  ako-operator/helm/ako-operator/values.yaml
  docs/ako_operator.md
  docs/akoconfig.md
  docs/install/operator.md
Labels: cla-not-required, cherry-pick

#1256 [GatewayAPI]Code to process objects during fullsync and bug fixes
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/gateway_model.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/objects/gateway_store.go
Labels: cla-not-required

#1257 [Gateway API] Bug fixes
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/status/status.go
  internal/nodes/avi_model_evh_nodes.go
  internal/rest/avi_evh_obj.go
  pkg/utils/constants.go
Labels: cla-not-required

#1222 AV-184860 : VS and Pools not deleted when multiple ingress use same infrasetting for shard size
  internal/objects/infrasetting.go
  internal/objects/store.go
  tests/ingresstests/ingressclass_test.go
Labels: cla-not-required
