Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2024-09, with the labels that each got.

#1498 AV-208589 RouteToChildVs mapping fixes
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model_rel.go
  internal/nodes/avi_model_evh_nodes.go
  tests/gatewayapitests/graphlayer/httproute_test.go
Labels: bug, cla-not-required, open-for-review

#1522 AV-216533 : Remove double encoding for URI
  pkg/utils/utils.go
Labels: cla-not-required

#1466 AV-210361 NodePortLocal support for AKO GatewayAPI
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/objects/gateway_store.go
  internal/lib/lib.go
  internal/nodes/dequeue_ingestion.go
  tests/gatewayapitests/npltests/gateway_npl_test.go
  tests/gatewayapitests/status/gateway_test.go
Labels: cla-not-required

#1515 Execute Gateway and HttpRoute in any order
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/gateway_model.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/objects/gateway_store.go
  ako-gateway-api/status/gateway_status.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/status/gateway_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
Labels: cla-not-required

#1509 AV-214519: AKO GW pod crashed with panic : interface {} is nil, not [……]objects.GatewayListenerStore
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/objects/gateway_store.go
  tests/gatewayapitests/npltests/gateway_npl_test.go
Labels: cla-not-required

#1525 add event in patch failure during status update
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/status/gateway_status.go
  ako-gateway-api/status/gatewayclass_status.go
  ako-gateway-api/status/httproute_status.go
  ako-gateway-api/status/status.go
  internal/lib/constants.go
  tests/gatewayapitests/graphlayer/httproute_test.go
Labels: cla-not-required

#1513 AV-217108 Fix for Hostmap cache not cleared in delete case for Insecure EVH
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_routeingr_hostname_shard.go
Labels: cla-not-required

#1514 AV-214469: Fix concurrent map read and write in vip network and node network map
  Makefile
  internal/lib/lib.go
Labels: cla-not-required

#1528 AV-210932 Improve UT runtime (servicesapitests)
  tests/integrationtest/lib.go
  tests/servicesapitests/servicesapi_l4_test.go
Labels: cla-not-required

#1486 AV-213944 Status update concurrency fix
  internal/lib/utils.go
  internal/status/ing_status.go
Labels: cla-not-required

#1533 AV-216533 : Remove double encoding for URI (#1522)
  Makefile
  internal/k8s/crdcontroller.go
  pkg/utils/utils.go
  tests/urltests/url_validation_test.go
Labels: cla-not-required

#1502 AV-199140: Add default HTTP policy set for default-backend 404
  ako-gateway-api/lib/constants.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  tests/gatewayapitests/graphlayer/gateway_test.go
  tests/gatewayapitests/graphlayer/httproute_test.go
Labels: cla-not-required

#1517 Skip Default cert cleanup when cleaning up a VS (#1496)
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick

#1532 AV-212390 Reverting BackendRefFilter changes
  ako-gateway-api/lib/constants.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/route_model.go
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/dequeue_nodes.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/status/httproute_test.go
Labels: cla-not-required

#1534 AV-209475 : Code and Documentation changes for AKO Operator 1.12.2 Release and RH Certification
  Dockerfile.ako-operator
  ako-operator/README.md
  ako-operator/api/v1alpha1/akoconfig_types.go
  ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
  ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
  ako-operator/config/secrets/secret.yaml
  ako-operator/controllers/configmap.go
  ako-operator/controllers/configmap_test.go
  ako-operator/controllers/crd.go
  ako-operator/controllers/role.go
  ako-operator/controllers/statefulset.go
  ako-operator/controllers/statefulset_test.go
  ako-operator/controllers/suite_test.go
  ako-operator/controllers/utils.go
  ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
  ako-operator/helm/ako-operator/crds/ako_vmware.com_l7rules.yaml
  docs/ako_operator.md
  docs/akoconfig.md
  docs/install/operator.md
Labels: cla-not-required

#1521 AV-210932 Improve UT runtime (ingresstests)
  tests/ingresstests/crd_test.go
  tests/ingresstests/ingress_annotation_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/l7_rest_test.go
  tests/ingresstests/lib.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_secure_route_test.go
Labels: cla-not-required

#1512 AV-210932 Improve UT runtime (evhtests, vippernstests)
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
  tests/evhtests/l7_evh_rest_test.go
Labels: cla-not-required

#1539 AV-209475 : Fix in Code and Documentation changes for AKO Operator 1.12.2 Release and RH Certification
  ako-operator/controllers/statefulset.go
Labels: cla-not-required

#1538 AV-218385 ChildVS Deletion should not update Gateway listener status
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/status/status.go
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/rest/avi_datascript.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_pool_group.go
Labels: cla-not-required

#1542 AV-217295 : Delete the sslkeycert for router-default-cert secret on reboot if it has no reference
  internal/rest/dequeue_nodes.go
Labels: cla-not-required
