Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2024-12, with the labels that each got.

#1574 AV-221865 process referred HTTPRoutes in gateway key
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/nodes/route_validator.go
  ako-gateway-api/objects/gateway_store.go
  tests/gatewayapitests/graphlayer/httproute_test.go
Labels: cla-not-required

#1597 AV-223474: Add gateway prefix to default backend HTTPPS
  Makefile
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  internal/lib/lib.go
Labels: cla-not-required

#1599 AV-223899: Added step create docker image tar and save it in mnt build path
  ako_cicd/jenkins/ci-build/save_build_on_mnt.sh
Labels: cla-not-required

#1602 fix(AV-224026): Added Read permission for other users on tar files
  ako_cicd/jenkins/ci-build/save_build_on_mnt.sh
Labels: cla-not-required

#1600 AV-223927 : Check PKIProfile Cache for existing pkiprofile while computing pkiprofile for new pool
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required

#1605 AV-224092: update srp tools download url
  ako_cicd/jenkins/ci-build/srp/srp_install.sh
Labels: cla-not-required

#1594 AV-222650 : Official documentation for Make httppolicy more k8s native for AKO repository
  docs/crds/hostrule.md
Labels: cla-not-required

#1603 AV-224027 : Documentation for HTTP/2 Support for AKO - Backend
  docs/crds/httprule.md
Labels: cla-not-required

#1590 AV-223112 Gateway API Documentation Update
  AKO_GATEWAY_CHANGELOG.md
  docs/gateway-api/gateway-api-v1.md
Labels: documentation, open-for-review

#1608 AV-224167: Fix: AKO is crashing when hostrule, with LogAllHeader field in AnalyticsPolicy field, is applied to an ingress
  internal/nodes/crd_translator.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
Labels: cla-not-required

#1609 BZ-3461406
  internal/k8s/advl4_controller.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
Labels: cla-not-required

#1613 Skip SE Group creation in VPC Mode
  ako-infra/avirest/netinfo_handler.go
  ako-infra/avirest/vpc_handler.go
  ako-infra/ingestion/avi_infra_controller.go
  cmd/infra-main/main.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/utils.go
  pkg/utils/avi_rest_utils.go
Labels: cla-not-required

#1616 Fixed cloud name value setting
  ako-infra/ingestion/avi_infra_controller.go
Labels: cla-not-required

#1614 AV-225892 : PKIProfile cache is not updated as cloud_ref is used in the get request URI
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#1607 AV-223871 Gateway Secret Handling Optimisation
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model.go
  docs/gateway-api/gateway-api-v1.md
  pkg/utils/utils.go
  tests/gatewayapitests/graphlayer/gateway_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required, open-for-review

#1617 Remove tailing slash in jenkins FQDN name
  ako_cicd/jenkins/ci-build/srp/save_and_submit_srp_data.sh
Labels: cla-not-required

#1621 AV-226253: Move ako helm chart files to ako directory inside buildpath
  ako_cicd/jenkins/ci-build/save_build_on_mnt.sh
Labels: cla-not-required
