Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2024-01, with the labels that each got.

#1347 AV-195886: Fix for missing SSL port on adding HostRule with SSL cert to insecure Dedicated VS
  Makefile
  internal/k8s/ako_init.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
Labels: cla-not-required

#1351 Cherry Pick: Fix for missing SSL port on adding HostRule with SSL cert …
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
Labels: cla-not-required, cherry-pick

#1355 AV-194029: Change description of nsx-T parameter in values.yaml
  CHANGELOG.md
  docs/README.md
  docs/akoconfig.md
  docs/install/helm.md
  helm/ako/values.yaml
Labels: documentation, cla-not-required

#1358 AV-196761 : Identify and reject irrelevant update events for Kubernetes objects in AKO
  internal/k8s/controller.go
Labels: cla-not-required

#1360 AV-196893: Accessing L4 CRD in another namespace
  internal/k8s/ako_init.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/service_model_rel.go
  tests/integrationtest/l4_crd_test.go
Labels: cla-not-required

#1345 AV-195873 AV-195878 Backend support for dualstack and status update
  ako-infra/avirest/handle_netinfo.go
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_vrf_translator.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  pkg/utils/utils.go
  tests/ingresstests/l7_graph_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1353 AV-189304 Fix Istio incorrect cache retrieval
  internal/k8s/controller.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#1365 AV-194029: Change description of nsx-T parameter in values.yaml
  CHANGELOG.md
  docs/README.md
  docs/akoconfig.md
  docs/install/helm.md
  helm/ako/values.yaml
Labels: cla-not-required

#1366 AV-197474: VRF support in vcenter cloud
  cmd/ako-main/main.go
  docs/akoconfig.md
  docs/values.md
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/cache/controller_obj_cache.go
  internal/k8s/crdcontroller.go
  internal/lib/avi_api.go
  internal/lib/control_config.go
  internal/lib/lib.go
Labels: cla-not-required

#1362 AV-196565 commit for L7Rule crd code
  helm/ako/crds/ako.vmware.com_hostrules.yaml
  helm/ako/crds/ako_vmware.com_l7rules.yaml
  helm/ako/templates/clusterrole.yaml
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/validator.go
  internal/lib/constants.go
  internal/lib/control_config.go
  internal/nodes/avi_model_nodes_utils.go
  internal/nodes/crd_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/objects/crdrules.go
  internal/status/crd_status.go
  pkg/apis/ako/v1alpha2/l7rule.go
  pkg/apis/ako/v1alpha2/register.go
  pkg/apis/ako/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ako/v1beta1/hostrule.go
  pkg/client/v1alpha2/clientset/versioned/typed/ako/v1alpha2/ako_client.go
  pkg/client/v1alpha2/clientset/versioned/typed/ako/v1alpha2/fake/fake_ako_client.go
  pkg/client/v1alpha2/clientset/versioned/typed/ako/v1alpha2/fake/fake_l7rule.go
  pkg/client/v1alpha2/clientset/versioned/typed/ako/v1alpha2/generated_expansion.go
  pkg/client/v1alpha2/clientset/versioned/typed/ako/v1alpha2/l7rule.go
  pkg/client/v1alpha2/informers/externalversions/ako/v1alpha2/interface.go
  pkg/client/v1alpha2/informers/externalversions/ako/v1alpha2/l7rule.go
  pkg/client/v1alpha2/informers/externalversions/generic.go
  pkg/client/v1alpha2/listers/ako/v1alpha2/expansion_generated.go
  pkg/client/v1alpha2/listers/ako/v1alpha2/l7rule.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required
