Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2024-08, with the labels that each got.

#1482 AV-208387 add tenant annotation for AMKO consumption
  internal/k8s/controller.go
  internal/k8s/crdcontroller.go
  internal/k8s/validator.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/crd_translator.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/dequeue_nodes.go
  internal/rest/k8s_utils.go
  internal/status/ing_status.go
  internal/status/multicluster_ing_status.go
  internal/status/route_status.go
  internal/status/svc_status.go
Labels: cla-not-required

#1479 AV-210326 : Adding support for NGINX annotation equivalents in AKO to configure HTTP Policy properties
  Makefile
  helm/ako/crds/ako.vmware.com_hostrules.yaml
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/k8s/validator.go
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_string_group.go
  internal/rest/dequeue_nodes.go
  pkg/apis/ako/v1beta1/hostrule.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/lib.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required

#1454 AV-209062: Wildcard fqdn support in Gateway
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/avi_model_l4_translator.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/nodes/route_model.go
  ako-gateway-api/objects/gateway_store.go
  pkg/utils/constants.go
  pkg/utils/utils.go
  tests/gatewayapitests/graphlayer/gateway_test.go
  tests/gatewayapitests/graphlayer/gatewayclass_test.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/gateway_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/status/gateway_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
Labels: cla-not-required

#1488 AV-213350: Enable endpointslices for gateways
  Makefile
  ako-gateway-api/k8s/ako_init.go
  ako-gateway-api/k8s/gateway_controller.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/gateway_model_rel.go
  cmd/gateway-api/main.go
  helm/ako/templates/statefulset.yaml
  internal/nodes/dequeue_ingestion.go
  tests/gatewayapitests/graphlayer/gateway_test.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/gateway_test.go
  tests/gatewayapitests/status/gateway_test.go
  tests/gatewayapitests/status/httproute_test.go
Labels: cla-not-required

#1496 AV-214324: Skip Default cert cleanup when cleaning up a VS
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#1487 AV-212214 Add URI encoding to rest calls
  ako-clean/cleanup.go
  internal/lib/avi_api.go
  internal/rest/rest_operation.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/utils.go
  tests/integrationtest/lib.go
  tests/scaletest/lib/utils.go
Labels: cla-not-required

#1497 upgrade alb-sdk to 30.2.1-post2
  go.mod
  go.sum
  vendor/github.com/vmware/alb-sdk/go/models/cloud.go
  vendor/github.com/vmware/alb-sdk/go/models/controller_properties.go
  vendor/github.com/vmware/alb-sdk/go/models/event_details.go
  vendor/github.com/vmware/alb-sdk/go/models/event_log.go
  vendor/github.com/vmware/alb-sdk/go/models/log_mgr_uber_event_details.go
  vendor/github.com/vmware/alb-sdk/go/models/memory_balancer_info.go
  vendor/github.com/vmware/alb-sdk/go/models/service_engine_group.go
  vendor/github.com/vmware/alb-sdk/go/models/uber_enum_message1.go
  vendor/github.com/vmware/alb-sdk/go/models/uber_enum_message2.go
  vendor/github.com/vmware/alb-sdk/go/session/avisession.go
  vendor/modules.txt
Labels: cla-not-required

#1499 AV-212214 Add URI encoding to rest calls (cherry-pick)
  internal/lib/avi_api.go
  internal/rest/rest_operation.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/utils.go
  tests/integrationtest/lib.go
  tests/scaletest/lib/utils.go
Labels: cla-not-required, cherry-pick

#1500 AV-214519: AKO GW pod crashed with panic : interface {} is nil, not [……]objects.GatewayListenerStore
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/objects/gateway_store.go
Labels: cla-not-required

#1494 AV-210932 Improve UT runtime (dedicatedvstests)
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/dedicatedvstests/l7_dedicated_rest_test.go
Labels: cla-not-required

#1493 AV-210932 Improve UT runtime (advl4tests)
  tests/advl4tests/advl4_hostname_test.go
Labels: cla-not-required

#1501 AV-212214 Fix uri encoding for query
  pkg/utils/utils.go
  tests/integrationtest/lib.go
Labels: cla-not-required, testing-in-progress

#1504 AV-212214: fix uri query encoding
  pkg/utils/utils.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1507 AV-216533 : Do not encode contents of the fields query param
  internal/k8s/crdcontroller.go
  pkg/utils/utils.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1505 AV-216010: Fix http policyset creation fails with error no port specified for httproute and Gateway without hostname
  ako-gateway-api/nodes/avi_model_l7_translator.go
  tests/gatewayapitests/graphlayer/httproute_test.go
Labels: cla-not-required

#1468 AV-210402: Fix: AKO-Gw: Child VS creation fails with duplicate FQDN in VHMatch creation
  ako-gateway-api/nodes/gateway_model_rel.go
  tests/gatewayapitests/graphlayer/gateway_test.go
  tests/gatewayapitests/graphlayer/gatewayclass_test.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/gateway_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/status/gateway_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
  tests/integrationtest/l4_crd_test.go
Labels: cla-not-required

#1495 Release notes 1.12.2
  CHANGELOG.md
  docs/install/helm.md
  docs/openshift/openshift_helm.md
Labels: cla-not-required

#1516 Compatibility Matrix for 1.12.2
  docs/README.md
Labels: cla-not-required
