Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2024-06, with the labels that each got.

#1448 AV-208875 : GatewayAPI UT fails as leader flag is not set for AKO
  tests/gatewayapitests/status/gateway_test.go
Labels: cla-not-required

#1449 AV-208875 : GatewayAPI UT fails as leader flag is not set for AKO
  tests/gatewayapitests/status/gateway_test.go
Labels: cla-not-required

#1434 AV-206565 Fix for AKO GW crash when HttpRoute attaching to one existing and one non existing gateway
  ako-gateway-api/k8s/validator.go
  ako-gateway-api/objects/gateway_store.go
  tests/gatewayapitests/status/gateway_test.go
  tests/gatewayapitests/status/httproute_test.go
Labels: cla-not-required, open-for-review

#1437 AV-207450 : L4Rule with SSL enabled not applied to L4 VS if license type is Enterprise with Cloud Services
  internal/lib/constants.go
  internal/nodes/avi_model_l4_translator.go
  internal/rest/avi_obj_vs.go
  tests/integrationtest/l4_crd_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1438 AV-207450 : L4Rule with SSL enabled not applied to L4 VS if license type is Enterprise with Cloud Services
  internal/lib/constants.go
  internal/nodes/avi_model_l4_translator.go
  internal/rest/avi_obj_vs.go
  tests/integrationtest/l4_crd_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required, cherry-pick

#1435 AV-205821 add external httppolicyset in cache
  internal/cache/controller_obj_cache.go
Labels: cla-not-required

#1443 AV-207312: Fix AKO crash in NSX-T shared L4 vip environment with no subdomain configured
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  tests/integrationtest/l4_service_test.go
Labels: cla-not-required

#1444 AV-207312: Fix AKO crash in NSX-T shared L4 vip environment with no subdomain configured
  buildsettings.json
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l4_translator.go
  tests/integrationtest/l4_service_test.go
Labels: cla-not-required

#1450 fix synchronisation issue in gatewayapi UT TestGatewayTLSToNoTLS
  tests/gatewayapitests/graphlayer/gateway_test.go
Labels: cla-not-required

#1440 AV-206693 Fix panic with Istio
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick

#1452 AV-207315-master: Support NSX-T in shared vip L4 services
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l7_translator.go
  tests/integrationtest/l4_service_test.go
Labels: cla-not-required

#1455 AV-209807 : AKO does not honour readines probe for pods when Antrea with NPL is used
  internal/lib/utils.go
  internal/nodes/avi_model_l4_translator.go
  tests/npltests/npl_pod_test.go
Labels: cla-not-required

#1441 AV-207705 Gateway API support for backendRef filters
  ako-gateway-api/lib/constants.go
  ako-gateway-api/lib/lib.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/dequeue_ingestion.go
  ako-gateway-api/nodes/route_model.go
  docs/roles/ako-admin.json
  docs/roles/ako-essential.json
  docs/roles/ako-tenant.json
  internal/cache/cache_utils.go
  internal/cache/controller_obj_cache.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_string_group.go
  internal/rest/dequeue_nodes.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/status/gateway_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
Labels: cla-not-required, open-for-review

#1453 AV-209065 Gateway container crash fix
  ako-gateway-api/nodes/avi_model_l7_translator.go
Labels: cla-not-required, open-for-review

#1461 AV-209807 : Adding UT to test AKO now honours readines probe for pods when Antrea with NPL is used
  tests/npltests/npl_pod_test.go
Labels: cla-not-required

#1460 AV-209807 : AKO does not honour readines probe for pods when Antrea with NPL is used
  internal/lib/utils.go
  internal/nodes/avi_model_l4_translator.go
  tests/npltests/npl_pod_test.go
Labels: cla-not-required, cherry-pick

#1459 AV-209807 : AKO does not honour readines probe for pods when Antrea with NPL is used
  internal/lib/utils.go
  internal/nodes/avi_model_l4_translator.go
  tests/cnitests/static_route_test.go
  tests/npltests/npl_pod_test.go
Labels: cla-not-required, cherry-pick

#1458 AV-209065 Gateway container crash fix
  ako-gateway-api/nodes/avi_model_l7_translator.go
Labels: cla-not-required, cherry-pick, open-for-review

#1467 AV-209807 : Adding doc changes for fix AKO does not honour readiness probe for pods when Antrea with NPL is used
  CHANGELOG.md
Labels: cla-not-required

#1469 AKO 1.13.1: Change min and max version of K8s and AviController as per AKO 1.13.1 release
  buildsettings.json
Labels: cla-not-required
