Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2024-07, with the labels that each got.

#1465 AV-206828 Fix AKO-GW container crash when NPL enabled
  ako-gateway-api/k8s/gateway_controller.go
  cmd/gateway-api/main.go
Labels: cla-not-required

#1462 ako gateway api image changes
  ako_cicd/jenkins/ci-build/ci-build.sh
  ako_cicd/jenkins/ci-build/save_build_on_registry.sh
  ako_cicd/jenkins/ci-build/srp/save_and_submit_srp_data.sh
Labels: cla-not-required

#1463 ako gateway api image changes
  ako_cicd/jenkins/ci-build/ci-build.sh
  ako_cicd/jenkins/ci-build/save_build_on_registry.sh
  ako_cicd/jenkins/ci-build/srp/save_and_submit_srp_data.sh
Labels: cla-not-required

#1474 AV-210878: Increase API timeout to 200 seconds
  CHANGELOG.md
  Dockerfile.ako
  Dockerfile.ako-gateway-api
  Dockerfile.ako-operator
  Makefile
  ako-infra/ingestion/vcf_k8s_controller.go
  buildsettings.json
  docs/README.md
  docs/ako_ha.md
  docs/install/helm.md
  docs/openshift/openshift_helm.md
  internal/k8s/ako_init.go
  internal/lib/avi_api.go
  pkg/utils/avi_rest_utils.go
  tests/scaletest/lib/utils.go
  version.yaml
Labels: cla-not-required

#1471 AV-210720: push docker images under specific branch folder
  ako_cicd/jenkins/ci-build/save_build_on_registry.sh
  ako_cicd/jenkins/ci-build/srp/save_and_submit_srp_data.sh
  ako_cicd/jenkins/ci-build/sync-image.sh
Labels: cla-not-required, do-not-merge

#1475 Av 210720 release 1.12.2
  ako_cicd/jenkins/ci-build/save_build_on_registry.sh
  ako_cicd/jenkins/ci-build/srp/save_and_submit_srp_data.sh
  ako_cicd/jenkins/ci-build/sync-image.sh
Labels: cla-not-required

#1477 AV-211008: Added build script required in jenkins file based jobs
  ako_cicd/jenkins/ci-build/build_promotion.sh
  ako_cicd/jenkins/ci-build/ci-build.sh
  ako_cicd/jenkins/ci-build/ci-srp-build.sh
  ako_cicd/jenkins/ci-build/save_build_on_mnt.sh
  ako_cicd/jenkins/ci-build/save_build_on_registry.sh
  ako_cicd/jenkins/ci-build/srp/save_and_submit_srp_data.sh
  ako_cicd/jenkins/ci-build/srp/srp_cleanup.sh
  ako_cicd/jenkins/ci-build/srp/srp_install.sh
  ako_cicd/jenkins/ci-build/sync-build.sh
  ako_cicd/jenkins/ci-build/sync-image.sh
  ako_cicd/jenkins/common-scripts/cleanup-docker-resources.sh
  ako_cicd/jenkins/common-scripts/decodeEncodedChangeset.py
  ako_cicd/jenkins/common-scripts/generateGitChangeLogReport.sh
  ako_cicd/jenkins/git-changelog/extract-injected-env-to-file.py
  ako_cicd/jenkins/git-changelog/gitChangeLogExtractor.groovy
  ako_cicd/jenkins/git-changelog/gitChangeLogExtractor.py
  ako_cicd/jenkins/git-changelog/requirements.txt
  ako_cicd/jenkins/git-changelog/templates/gitChangeLogReportTemplate.html
  ako_cicd/jenkins/git-changelog/test/changelog.json
Labels: cla-not-required

#1447 AV-207315-master: Support NSX-T in shared vip L4 services
  internal/nodes/avi_model_advl4_translator.go
  internal/nodes/avi_model_l7_translator.go
  tests/integrationtest/l4_service_test.go
Labels: cla-not-required

#1470 AV-210421 StringGroup cache fix for Gateway
  ako-gateway-api/lib/constants.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  internal/cache/controller_obj_cache.go
  internal/rest/avi_obj_string_group.go
Labels: open-for-review

#1473 AV-210402: Release-1.12.2: Fix: AKO-Gw: Child VS creation fails with duplicate FQDN in VHMatch creation
  ako-gateway-api/nodes/gateway_model_rel.go
  tests/gatewayapitests/graphlayer/gateway_test.go
  tests/gatewayapitests/graphlayer/gatewayclass_test.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/gateway_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/status/gateway_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
Labels: cla-not-required

#1476 Added make target for multitenancy UTs
  Makefile
  tests/multitenancytests/multitenancy_infrasetting_ako_svc_test.go
  tests/multitenancytests/multitenancy_infrasetting_evh_test.go
  tests/multitenancytests/multitenancy_infrasetting_ingress_test.go
Labels: cla-not-required

#1485 Gateway UT fixes
  tests/gatewayapitests/utils.go
Labels: cla-not-required

#1480 Create a single sslkey per Tenant for default secret
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  tests/ingresstests/ingress_annotation_test.go
Labels: cla-not-required

#1481 AV-210248: Implement Endpoint Slice for Pod graceful shutdown
  Makefile
  cmd/ako-main/main.go
  helm/ako/templates/clusterrole.yaml
  helm/ako/templates/configmap.yaml
  helm/ako/templates/statefulset.yaml
  helm/ako/values.yaml
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/control_config.go
  internal/lib/lib.go
  internal/nodes/avi_model_l4_translator.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_model_nodes_utils.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/rest/avi_obj_pool.go
  pkg/apis/ako/v1alpha2/common.go
  pkg/apis/ako/v1alpha2/doc.go
  pkg/apis/ako/v1alpha2/l4rule.go
  pkg/apis/ako/v1alpha2/l7rule.go
  pkg/apis/ako/v1alpha2/register.go
  pkg/apis/ako/v1alpha2/ssorule.go
  pkg/utils/constants.go
  pkg/utils/types.go
  pkg/utils/utils.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_rest_test.go
  tests/ingresstests/ingressclass_test.go
  tests/ingresstests/l7_graph_test.go
  tests/ingresstests/l7_nodeport_test.go
  tests/ingresstests/l7_rest_test.go
  tests/ingresstests/lib.go
  tests/integrationtest/l4_service_test.go
  tests/integrationtest/lib.go
  tests/k8stest/controller_test.go
  tests/npltests/npl_pod_test.go
  tests/oshiftroutetests/lib.go
  tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
  tests/oshiftroutetests/oshift_route_namespace_sync_test.go
  tests/oshiftroutetests/oshift_route_passthrough_test.go
  tests/oshiftroutetests/oshift_route_rest_test.go
  tests/oshiftroutetests/oshift_secure_route_test.go
Labels: cla-not-required
