Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2024-05, with the labels that each got.

#1418 AV-205715 : Increase timeout for avi client to two minutes
  ako-infra/ingestion/vcf_k8s_controller.go
  internal/k8s/ako_init.go
  internal/lib/avi_api.go
  pkg/utils/avi_rest_utils.go
  tests/scaletest/lib/utils.go
Labels: cla-not-required

#1413 AV-205437 Static Route fixes
  internal/nodes/avi_vrf_translator.go
  tests/cnitests/static_route_test.go
Labels: cla-not-required

#1395 AV-203576 Documentation update for Gateway
  AKO_GATEWAY_CHANGELOG.md
  docs/gateway-api/gateway-api-v1.md
Labels: documentation, cla-not-required

#1419 AV-205437 Static Route fix
  internal/nodes/avi_vrf_translator.go
  tests/cnitests/static_route_test.go
Labels: cla-not-required

#1421 AV-205437 Changelog Update
  CHANGELOG.md
Labels: documentation, cla-not-required

#1422 Change K8 min version to 1.25 for 1.12.1
  buildsettings.json
Labels: cla-not-required

#1420 AV-205437 Static Route fix
  internal/nodes/avi_vrf_translator.go
  tests/cnitests/static_route_test.go
Labels: cla-not-required

#1424 AV-205976 : disabling status update for vs and pool from follower
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#1427 Update compatibility matrix for AKO 1.12.1.
  docs/README.md
Labels: cla-not-required, cherry-pick-required

#1426 AKO-1.12.1 Release Notes
  CHANGELOG.md
Labels: cla-not-required, cherry-pick-required

#1431 Update helm.md. Add vrfName parameters details
  docs/install/helm.md
Labels: cla-not-required, cherry-pick-required

#1430 Update CHANGELOG.md
  CHANGELOG.md
Labels: cla-not-required, cherry-pick-required

#1429 Gateway API Doc fix
  docs/gateway-api/gateway-api-v1.md
Labels: documentation, cla-not-required, open-for-review

#1433 AV-206693 Fix panic with Istio
  internal/rest/dequeue_nodes.go
Labels: cla-not-required

#1423 AV-205976 : disabling status update for vs and pool from follower
  internal/rest/avi_obj_vs.go
Labels: cla-not-required

#1436 AV-206315: Added condition to sync AKO_GATEWAY_API_IMAGE_NAME only fo…
  ako_cicd/jenkins/ci-build/sync-image.sh
Labels: cla-not-required

#1439 AV-206315: Added condition to sync AKO_GATEWAY_API_IMAGE_NAME only fo…
  ako_cicd/jenkins/ci-build/sync-image.sh
Labels: cla-not-required
