Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2025-02, with the labels that each got.

#1628 AV-226524 : Document limitation for CONFIG_UPDATE to update httppolicyset on Shared Parent VS is failing because of system limit NUM_HTTP_POLICIES_PER_VS reached
  docs/crds/hostrule.md
Labels: cla-not-required

#1632 AV-228261 : Add release notes for AKO 1.13.1 release
  AKO_GATEWAY_CHANGELOG.md
  CHANGELOG.md
  docs/install/helm.md
  docs/openshift/openshift_helm.md
Labels: cla-not-required

#1638 AV-228826 Gateway api documentation update
  docs/gateway-api/gateway-api-v1.md
Labels: documentation

#1644 Cherry pick 1.13.1 doc changes to master
  AKO_GATEWAY_CHANGELOG.md
  CHANGELOG.md
  docs/crds/hostrule.md
  docs/install/helm.md
  docs/openshift/openshift_helm.md
Labels: cherry-pick

#1656 AV-226793 : For shared-vip, when service type is changed from LB to ClusterIP and reverted, ako does not create the VS
  Makefile
  buildsettings.json
  docs/README.md
  internal/nodes/dequeue_ingestion.go
  tests/integrationtest/l4_crd_test.go
  tests/integrationtest/l4_service_test.go
Labels: cherry-pick

#1652 AV-226793 : For shared-vip, when service type is changed from LB to ClusterIP and reverted, ako does not create the VS
  internal/nodes/dequeue_ingestion.go
  tests/integrationtest/l4_crd_test.go
  tests/integrationtest/l4_service_test.go
Labels: cherry-pick

#1657 AV-228558 use correct tenant during model creation for passthrough host
  internal/nodes/avi_model_routeingr_hostname_shard.go
  tests/multitenancytests/multitenancy_infrasetting_ingress_test.go
Labels: cherry-pick
