Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2025-03, with the labels that each got.

#1665 AV-231547:Regex path support in GatewayAPI
  ako-gateway-api/lib/constants.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/route_model.go
  ako-gateway-api/nodes/route_validator.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/npltests/gateway_npl_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1658 Changed ClusterName in VPC Mode and fixed cleanup script
  ako-clean/cleanup.go
  internal/lib/lib.go
  pkg/utils/constants.go
Labels: cherry-pick

#1660 AV-231510 Troubleshoot doc update for AV-230178
  docs/troubleshooting/troubleshooting.md
Labels: documentation, open-for-review

#1671 AV-231550: AKO doesn't apply hostrule with Shared Vs FQDN if there is no DNS present in the cloud
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/crd_translator.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1673 AV-229617 : app-root not configured in httppolicyset when openshift routes do not have ports specified (#1664)
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_hostname_shard.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/crd_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/avi_obj_httpps.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/oshift_crd_test.go
  tests/oshiftroutetests/oshift_route_model_test.go
Labels: cla-not-required, cherry-pick

#1672 AV-228668: Fix: tenant name with special characters (#1654)
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/rest/avi_datascript.go
  internal/rest/avi_evh_obj.go
  internal/rest/avi_obj_httpps.go
  internal/rest/avi_obj_l4ps.go
  internal/rest/avi_obj_pool.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/avi_pool_group.go
  internal/rest/ssl_key_certificate.go
Labels: cla-not-required

#1675 Av 231547 release 1.13.2
  ako-gateway-api/lib/constants.go
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/route_model.go
  ako-gateway-api/nodes/route_validator.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/npltests/gateway_npl_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1679 Fix UT Failure in evh
  tests/evhtests/l7_evh_crd_test.go
Labels: cla-not-required

#1678 AV-232361: Use update instead of patch for making list empty
  ako-gateway-api/status/gateway_status.go
  tests/evhtests/l7_evh_graph_test.go
Labels: cla-not-required

#1674 AV-231550: AKO doesn't apply hostrule with Shared Vs FQDN if there is no DNS present in the cloud (Cherry Pick)
  internal/lib/lib.go
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/avi_model_l7_translator.go
  internal/nodes/crd_translator.go
  tests/evhtests/l7_evh_crd_test.go
  tests/ingresstests/crd_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required

#1677 AV-228152 Check if Vs is present in cache before bulk delete of route status
  internal/status/route_status.go
Labels: cla-not-required, cherry-pick

#1683 AV-152331 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: cla-not-required

#1684 AV-230611 do partial cache refresh before rest layer retry for follower
  internal/rest/dequeue_nodes.go
Labels: cla-not-required, cherry-pick

#1662 AV-231513 HTTPRoute Rewrite Filter
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/nodes/route_model.go
  ako-gateway-api/nodes/route_validator.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
Labels: enhancement, open-for-review

#1694 AV-232211 : Stale string groups not getting cleaned on controller inspite of multiple AKO reboots (#1688)
  internal/cache/controller_obj_cache.go
Labels: cla-not-required, cherry-pick

#1693 AV-231513 release-1.13.2 cherry pick
  ako-gateway-api/nodes/avi_model_l7_translator.go
  ako-gateway-api/nodes/gateway_model_rel.go
  ako-gateway-api/nodes/route_model.go
  ako-gateway-api/nodes/route_validator.go
  tests/gatewayapitests/graphlayer/httproute_test.go
  tests/gatewayapitests/ingestion/httproute_test.go
  tests/gatewayapitests/status/httproute_test.go
  tests/gatewayapitests/utils.go
Labels: cla-not-required, cherry-pick

#1698 AV-232182: Retry on url error(client)
  internal/rest/dequeue_nodes.go
  pkg/utils/types.go
Labels: cla-not-required

#1697 AV-232378: Fix panic in gateway
  ako-gateway-api/lib/lib.go
Labels: cla-not-required

#1704 AV-232009 Fix label creation on SE group by Gateway container
  cmd/gateway-api/main.go
Labels: cla-not-required, cherry-pick, open-for-review
