Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2025-04, with the labels that each got.

#1709 AV-232182: Retry on url error(client) [cherry-pick]
  internal/rest/dequeue_nodes.go
  pkg/utils/types.go
Labels: cla-not-required

#1707 AV-232378: Fix panic in gateway
  ako-gateway-api/lib/lib.go
Labels: cla-not-required

#1712 correct unittests
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/ingresstests/crd_test.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required, cherry-pick

#1710 AV-232413 : Encode pg and pool name in SNI mode for ingress/route host with no path defined
  internal/nodes/crd_translator.go
  tests/dedicatedvstests/l7_dedicated_crd_test.go
  tests/dedicatedvstests/l7_dedicated_graph_test.go
  tests/ingresstests/crd_test.go
  tests/ingresstests/l7_rest_test.go
  tests/integrationtest/lib.go
  tests/oshiftroutetests/lib.go
  tests/oshiftroutetests/oshift_crd_test.go
Labels: cla-not-required, cherry-pick

#1713 AV-233357: Fetch package details from Broadcom interanl go registry
  ako_cicd/jenkins/ci-build/ci-srp-build.sh
Labels: cla-not-required

#1701 AV-227367 check if vsuuid exists in cache before deleting ingress status
  internal/status/ing_status.go
Labels: cla-not-required

#1696 AV-233670: VIP Per Namespace: Do not add auto fqdn to L7 VS
  internal/lib/lib.go
  tests/evhtests/l7_evh_crd_test.go
  tests/evhtests/l7_evh_graph_test.go
  tests/evhtests/l7_evh_ingressclass_test.go
Labels: cla-not-required

#1703 AV-232009 Fix label creation on SE group by Gateway container
  cmd/gateway-api/main.go
Labels: bug, cla-not-required, open-for-review

#1715 AV-227367 check if vsuuid exists in cache before deleting ingress status
  internal/status/ing_status.go
Labels: cla-not-required, cherry-pick

#1718 AV-233357: Fetch package details from Broadcom interanl go registry
  ako_cicd/jenkins/ci-build/ci-srp-build.sh
Labels: cla-not-required

#1719 AV-233357: Fetch package details from Broadcom interanl go registry
  ako_cicd/jenkins/ci-build/ci-srp-build.sh
Labels: cla-not-required

#1717 AV-235192: Import alb-sdk package into AKO
  go.mod
  go.sum
  vendor/github.com/vmware/alb-sdk/go/session/avisession.go
  vendor/modules.txt
Labels: cla-not-required

#1720 AV-233357: Fetch package details from Broadcom interanl go registry
  ako_cicd/jenkins/ci-build/ci-srp-build.sh
Labels: cla-not-required

#1716 AV-235192: Import alb-sdk package into AKO
  go.mod
  go.sum
  vendor/github.com/vmware/alb-sdk/go/session/avisession.go
  vendor/modules.txt
Labels: cla-not-required

#1724 Added support for Proxy Enabled Application Profile in WCP env
  ako-clean/cleanup.go
  internal/k8s/advl4_controller.go
  internal/k8s/ako_init.go
  internal/lib/constants.go
  internal/lib/lib.go
  internal/lib/utils.go
  internal/nodes/avi_model_advl4_translator.go
  tests/advl4tests/advl4_hostname_test.go
  tests/advl4tests/informers/advl4_informer_test.go
  tests/advl4tests/setup.go
Labels: cla-not-required

#1723 AV-232305 Gateway doc update with httproute rewrite filter limitations
  docs/gateway-api/gateway-api-v1.md
Labels: documentation, cla-not-required, open-for-review

#1705 AV-232614 Static Route fixes
  .github/workflows/go.yml
  internal/lib/utils.go
  internal/nodes/avi_model_nodes.go
  internal/nodes/avi_vrf_translator.go
  internal/nodes/dequeue_ingestion.go
  internal/rest/avi_obj_vrf.go
  tests/cnitests/static_route_test.go
  tests/integrationtest/static_route_test.go
Labels: cla-not-required, open-for-review

#1726 AV-232305 Gateway doc update with httproute rewrite filter limitation
  docs/gateway-api/gateway-api-v1.md
Labels: documentation, cherry-pick, open-for-review

#1744 AV-236691 revert partial cache refresh for follower
  internal/rest/dequeue_nodes.go
Labels: cherry-pick

#1749 [release-1.13.2] Fix eks network validation check 1.13.2
  internal/k8s/crdcontroller.go
Labels: cherry-pick

#1740 BZ-3508026: Changed AVIInfraSettingCR Name
  ako-infra/avirest/netinfo_handler.go
  ako-infra/avirest/vpc_handler.go
  internal/lib/lib.go
  internal/rest/avi_obj_vsvip.go
  tests/infratests/akoinfra_test.go
Labels: cherry-pick

#1685 Include Pool name in L4 Policy checksum calculation
  internal/cache/controller_obj_cache.go
  internal/lib/lib.go
  internal/nodes/avi_model_nodes.go
  internal/rest/avi_obj_l4ps.go
Labels: cherry-pick

#1741 AV-236996 Gateway API doc update
  docs/gateway-api/gateway-api-v1.md
Labels: documentation, open-for-review

#1747 AV-236996 Gateway API doc update
  docs/gateway-api/gateway-api-v1.md
Labels: documentation, cherry-pick, open-for-review

#1755 AV-237682 Disable se group label updation by follower ako
  internal/cache/controller_obj_cache.go
  internal/lib/avi_api.go
Labels: bug, cherry-pick, open-for-review
