Repository vmware/load-balancer-and-ingress-services-for-kubernetes, pull requests merged in 2025-01, with the labels that each got.

#1619 AV-226216 : Documentation for pool placement settings not configured with the node network for vCenter cloud in NodePort mode
  docs/values.md
  helm/ako/values.yaml
Labels: cla-not-required

#1620 AV-226218 : Documentation for adding support in AKO for Openshift Route object with subdomain specified
  docs/install/helm.md
  docs/values.md
  helm/ako/values.yaml
Labels: cla-not-required

#1564 AV-220244: Check for Namespace annotation and VS lb svc for determining the correct cloud
  ako-infra/ingestion/avi_infra_controller.go
  cmd/infra-main/main.go
  internal/cache/controller_obj_cache.go
  tests/avimockobjects/CLOUD_NSXT1_mock.json
  tests/avimockobjects/kube-apiserver-lb-svc-vs_mock.json
  tests/infratests/akoinfra_test.go
  tests/integrationtest/lib.go
Labels: cla-not-required, cherry-pick

#1612 BZ-3461406: 1.Fixed vrf related issues with vsvip post 2.Retry Ingress for change of tenant or infrasetting in NS annotation
  internal/k8s/advl4_controller.go
  internal/nodes/avi_model_evh_nodes.go
Labels: cla-not-required, cherry-pick

#1611 AV-224356: Documentation for Restricting FQDN to single namespace
  docs/ako_fqdnrestriction.md
  docs/install/helm.md
  docs/values.md
Labels: cla-not-required

#1625 Add LB Class validation and SharedVIPKey on NS updation
  internal/k8s/controller.go
  internal/nodes/dequeue_ingestion.go
Labels: cla-not-required

#1626 Cherry-pick WCP changes to the master
  ako-infra/avirest/netinfo_handler.go
  ako-infra/avirest/networking_handler.go
  ako-infra/avirest/vpc_handler.go
  ako-infra/ingestion/avi_infra_controller.go
  cmd/ako-main/main.go
  cmd/infra-main/main.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/k8s/controller.go
  internal/lib/dynamic_client.go
  internal/lib/lib.go
  internal/lib/utils.go
  internal/nodes/dequeue_ingestion.go
  internal/nodes/ingress_model_rel.go
  internal/nodes/validator.go
  internal/rest/avi_obj_vs.go
  internal/rest/avi_obj_vsvip.go
  internal/rest/dequeue_nodes.go
  internal/rest/k8s_utils.go
  internal/status/advl4_status.go
  internal/status/svc_status.go
  pkg/utils/avi_rest_utils.go
  pkg/utils/utils.go
  tests/infratests/akoinfra_test.go
Labels: cla-not-required, cherry-pick

#1631 AV-228042 Fixed pagination issue in GetAllTenants and Populatecache changes
  ako-clean/cleanup.go
  internal/cache/controller_obj_cache.go
  internal/k8s/ako_init.go
  internal/lib/utils.go
Labels: cla-not-required

#1630 AV-22790: Delete VS on same fqdn different namespace in Dedicated mode
  internal/nodes/avi_model_evh_nodes.go
  internal/nodes/hostname_cache.go
  tests/dedicatedevhtests/l7_evh_crd_test.go
Labels: cla-not-required

#1635 Gateway document Update
  docs/gateway-api/gateway-api-v1.md
Labels: documentation

#1624 AV-226852 documentation for AKO multitenancy
  docs/ako_tenancy.md
Labels: cla-not-required
